#ifndef WI_dirt_layout_h
#define WI_dirt_layout_h
/* $Id: dirt_layout.h,v 1.19 92/01/26 15:28:35 rlh2 Rel $
 *
 * X Toolkit program layout header file.
 * This file contains all the definitions of the static parts
 * of the user interface.
 */

/*
 * This file was generated by the DIRT interface editor
 *	Author: Richard Hesketh / rlh2@ukc.ac.uk
 *	Version: 1.3 (Wc) of July 1990
 *
 * Generated for rlh2 on Sun Jan 26 15:25:30 1992
 */

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Xaw/Simple.h>
#include <X11/Xaw/Viewport.h>
#include <X11/Xaw/SimpleMenu.h>
#include <X11/Xaw/StripChart.h>
#include <X11/Xaw/Scrollbar.h>
#include <X11/Xaw/Logo.h>
#include <X11/Xaw/Toggle.h>
#include <X11/Xaw/Mailbox.h>
#include <X11/Xaw/Grip.h>
#include <X11/Xaw/Label.h>
#include <X11/Xaw/Form.h>
#include <X11/Xaw/Dialog.h>
#include <X11/Xaw/Command.h>
#include <X11/Xaw/Clock.h>
#include <X11/Xaw/Box.h>
#include <X11/Xukc/Error.h>
#include <X11/Xukc/ScrollList.h>
#include <X11/Xaw/Paned.h>
#include <X11/Core.h>
#include <X11/Xukc/Viewport.h>
#include <X11/Xukc/Value.h>
#include <X11/Xukc/Toggle.h>
#include <X11/Xaw/AsciiText.h>
#include <X11/Shell.h>
#include <X11/Xukc/Command.h>
#include <X11/Xukc/Med3Menu.h>
#include <X11/Xukc/Label.h>
#include <X11/Xukc/Layout.h>

struct w_connections {
	Widget *layout;
	Widget *w1;
	Widget *w2;
	Positioning pos;
};

/* WIDGET/OBJECT class registration list */

struct w_classes {
	WidgetClass *class;
	String class_name;
};

/* WIDGET/OBJECT constructor registration list */

struct w_constructors {
	Widget (*constructor)();
	String constructor_name;
};

struct w_classes WI_dirt_classes[] = {
	{ &simpleWidgetClass, "simpleWidgetClass" },
	{ &viewportWidgetClass, "viewportWidgetClass" },
	{ &simpleMenuWidgetClass, "simpleMenuWidgetClass" },
	{ &stripChartWidgetClass, "stripChartWidgetClass" },
	{ &scrollbarWidgetClass, "scrollbarWidgetClass" },
	{ &logoWidgetClass, "logoWidgetClass" },
	{ &toggleWidgetClass, "toggleWidgetClass" },
	{ &mailboxWidgetClass, "mailboxWidgetClass" },
	{ &gripWidgetClass, "gripWidgetClass" },
	{ &labelWidgetClass, "labelWidgetClass" },
	{ &formWidgetClass, "formWidgetClass" },
	{ &dialogWidgetClass, "dialogWidgetClass" },
	{ &commandWidgetClass, "commandWidgetClass" },
	{ &clockWidgetClass, "clockWidgetClass" },
	{ &boxWidgetClass, "boxWidgetClass" },
	{ &ukcErrorWidgetClass, "ukcErrorWidgetClass" },
	{ &ukcScrListWidgetClass, "ukcScrListWidgetClass" },
	{ &panedWidgetClass, "panedWidgetClass" },
	{ &ukcViewportWidgetClass, "ukcViewportWidgetClass" },
	{ &ukcValueWidgetClass, "ukcValueWidgetClass" },
	{ &ukcToggleWidgetClass, "ukcToggleWidgetClass" },
	{ &asciiTextWidgetClass, "asciiTextWidgetClass" },
	{ &ukcCommandWidgetClass, "ukcCommandWidgetClass" },
	{ &ukcMed3MenuWidgetClass, "ukcMed3MenuWidgetClass" },
	{ &ukcLabelWidgetClass, "ukcLabelWidgetClass" },
	{ &ukcLayoutWidgetClass, "ukcLayoutWidgetClass" },
};

struct w_constructors WI_dirt_constructors[] = {
	{ XtCreateTransientShell, "XtCreateTransientShell" },
	{ XtCreateTopLevelShell, "XtCreateTopLevelShell" },
};

/* WIDGET ID. VARIABLES */

Widget WI_dirt;
Widget  WI_main_layout;
Widget   WI_main_title;
Widget   WI_main_menu;
Widget   WI_create_pressup;
Widget   WI_create_shell;
Widget    WI_create_layout;
Widget     WI_create_hide;
Widget     WI_create_name_label;
Widget     WI_create_name_entry;
Widget     WI_create_class_label;
Widget     WI_create_class_entry;
Widget     WI_app_x_locked_toggle;
Widget     WI_app_x_pos_value;
Widget     WI_app_y_locked_toggle;
Widget     WI_app_y_pos_value;
Widget     WI_app_width_locked_toggle;
Widget     WI_app_width_value;
Widget     WI_app_height_locked_toggle;
Widget     WI_app_height_value;
Widget     WI_app_border_label;
Widget     WI_app_border_value;
Widget     WI_app_new;
Widget     WI_app_delete;
Widget     WI_app_resources_title;
Widget     WI_app_resources_viewport;
Widget     WI_app_comments;
Widget     WI_app_blank;
Widget     WI_create_title;
Widget   WI_new_pressup;
Widget   WI_new_shell;
Widget    WI_new_layout;
Widget     WI_new_hide;
Widget     WI_new_name_label;
Widget     WI_new_name_entry;
Widget     WI_new_class_label;
Widget     WI_new_class_entry;
Widget     WI_new_parent_label;
Widget     WI_new_parent_entry;
Widget     WI_pick_parent;
Widget     WI_new_x_pos_label;
Widget     WI_new_x_pos_value;
Widget     WI_new_y_pos_label;
Widget     WI_new_y_pos_value;
Widget     WI_new_width_label;
Widget     WI_new_width_value;
Widget     WI_new_height_label;
Widget     WI_new_height_value;
Widget     WI_new_border_label;
Widget     WI_new_border_value;
Widget     WI_new_managed;
Widget     WI_new_pane;
Widget      WI_class_layout;
Widget       WI_class_title;
Widget       WI_class_examples;
Widget       WI_class_list;
Widget      WI_new_resources_layout;
Widget       WI_new_resources_title;
Widget       WI_new_resources_viewport;
Widget     WI_new_title;
Widget     WI_new_create;
Widget     WI_new_delete;
Widget     WI_new_deferred;
Widget   WI_instance_pressup;
Widget   WI_instance_shell;
Widget    WI_instance_layout;
Widget     WI_instance_hide;
Widget     WI_instance_name_label;
Widget     WI_instance_name_entry;
Widget     WI_instance_class_label;
Widget     WI_instance_class_entry;
Widget     WI_instance_parent_label;
Widget     WI_instance_parent_entry;
Widget     WI_x_pos_label;
Widget     WI_x_pos_value;
Widget     WI_y_pos_label;
Widget     WI_y_pos_value;
Widget     WI_width_label;
Widget     WI_width_value;
Widget     WI_height_label;
Widget     WI_height_value;
Widget     WI_border_label;
Widget     WI_border_value;
Widget     WI_instance_managed;
Widget     WI_instance_resources_title;
Widget     WI_instance_resources_viewport;
Widget     WI_edit_comments;
Widget     WI_instance_title;
Widget     WI_instance_deferred;
Widget   WI_instance_list_title;
Widget   WI_instance_list;
Widget   WI_action_stubs_pressup;
Widget   WI_action_stubs_shell;
Widget    WI_action_stubs_layout;
Widget     WI_action_stubs_hide;
Widget     WI_action_stubs_label;
Widget     WI_action_stubs_entry;
Widget     WI_action_stubs_list_label;
Widget     WI_action_stubs_list;
Widget     WI_action_stubs_register;
Widget     WI_action_stubs_title;
Widget   WI_callback_stubs_pressup;
Widget   WI_callback_stubs_shell;
Widget    WI_callback_stubs_layout;
Widget     WI_callback_stubs_hide;
Widget     WI_callback_stubs_register;
Widget     WI_callback_stubs_label;
Widget     WI_callback_stubs_entry;
Widget     WI_callback_stubs_list_label;
Widget     WI_callback_stubs_list;
Widget     WI_callback_stubs_title;
Widget   WI_trans_shell;
Widget    WI_translations_layout;
Widget     WI_trans_apply_button;
Widget     WI_trans_hide_button;
Widget     WI_events_label;
Widget     WI_actions_label;
Widget     WI_trans_title;
Widget     WI_events_view;
Widget     WI_current_translations;
Widget     WI_actions_view;
Widget     WI_trans_v_pane;
Widget      WI_trans_text;
Widget      WI_trans_error;
Widget   WI_error_shell;
Widget    WI_error_trap;
Widget   WI_delete_dialog_shell;
Widget    WI_delete_dialog_layout;
Widget     WI_delete_dialog_title;
Widget     WI_delete_dialog_object;
Widget     WI_delete_dialog_yes;
Widget     WI_delete_dialog_no;
Widget   WI_file_dialog_shell;
Widget    WI_file_dialog_layout;
Widget     WI_file_dialog_title;
Widget     WI_file_dialog_spec_prefix;
Widget     WI_file_dialog_spec_label;
Widget     WI_file_dialog_save_spec;
Widget     WI_file_dialog_save_code;
Widget     WI_file_dialog_save_both;
Widget     WI_file_dialog_save_cancel;
Widget     WI_file_dialog_code_prefix;
Widget     WI_file_dialog_code_label;
Widget     WI_file_dialog_save_resources;
Widget   WI_templates_pressup;
Widget   WI_templates_shell;
Widget    WI_templates_pane;
Widget     WI_templates_layout;
Widget      WI_templates_hide;
Widget      WI_templates_name;
Widget      WI_templates_name_entry;
Widget      WI_templates_notes_title;
Widget      WI_templates_notes;
Widget      WI_templates_title;
Widget      WI_template_create;
Widget     WI_templates_avail_layout;
Widget      WI_templates_avail_title;
Widget      WI_templates_available;
Widget     WI_templates_heir_layout;
Widget      WI_templates_heir_title;
Widget      WI_templates_heirarchy;
Widget   WI_template_building_shell = NULL; /* deferred creation */
Widget    WI_template_building_layout = NULL; /* deferred creation */
Widget     WI_template_building_title = NULL; /* deferred creation */
Widget     WI_template_building_hide = NULL; /* deferred creation */
Widget     WI_template_building_area = NULL; /* deferred creation */
Widget   WI_comment_shell;
Widget    WI_comment_pane;
Widget     WI_comment_layout;
Widget      WI_comment_title;
Widget      WI_comment_hide;
Widget      WI_comment_text;
Widget     WI_help_layout;
Widget      WI_help_title;
Widget      WI_help_text;
Widget   WI_load_dialog_shell;
Widget    WI_load_dialog_layout;
Widget     WI_load_dialog_title;
Widget     WI_load_dialog_prefix_label;
Widget     WI_load_dialog_spec_prefix;
Widget     WI_load_dialog_load;
Widget     WI_load_dialog_cancel;
Widget   WI_help_shell;
Widget    WI_context_help_layout;
Widget     WI_context_help_title;
Widget     WI_context_help_hide;
Widget     WI_help_resource_title;
Widget     WI_help_pane;
Widget      WI_help_resource_layout;
Widget       WI_help_resource_label;
Widget       WI_help_resource_text;
Widget      WI_help_type_layout;
Widget       WI_help_type_text;
Widget       WI_help_type_label;
Widget      WI_help_class_layout;
Widget       WI_help_class_label;
Widget       WI_help_class_text;
Widget   WI_athena_examples = NULL; /* deferred creation */
Widget    WI_athena_examples_layout = NULL; /* deferred creation */
Widget     WI_athena_examples_title = NULL; /* deferred creation */
Widget     WI_athena_examples_hide = NULL; /* deferred creation */
Widget     WI_athena_box = NULL; /* deferred creation */
Widget      WI_athena_clock = NULL; /* deferred creation */
Widget      WI_athena_command = NULL; /* deferred creation */
Widget      WI_athena_dialog_box = NULL; /* deferred creation */
Widget       WI_athena_dialog_box_button = NULL; /* deferred creation */
Widget     WI_athena_editable_text = NULL; /* deferred creation */
Widget     WI_athena_form = NULL; /* deferred creation */
Widget      WI_f1 = NULL; /* deferred creation */
Widget      WI_f2 = NULL; /* deferred creation */
Widget      WI_f3 = NULL; /* deferred creation */
Widget     WI_athena_examples_box_label = NULL; /* deferred creation */
Widget     WI_athena_form_label = NULL; /* deferred creation */
Widget     WI_athena_label = NULL; /* deferred creation */
Widget     WI_athena_grip = NULL; /* deferred creation */
Widget     WI_athena_grip_label = NULL; /* deferred creation */
Widget     WI_athena_mailbox = NULL; /* deferred creation */
Widget     WI_athena_paned = NULL; /* deferred creation */
Widget      WI_p1 = NULL; /* deferred creation */
Widget      WI_p2 = NULL; /* deferred creation */
Widget      WI_p3 = NULL; /* deferred creation */
Widget     WI_athena_paned_label = NULL; /* deferred creation */
Widget     WI_athena_toggle_label = NULL; /* deferred creation */
Widget     WI_athena_toggle = NULL; /* deferred creation */
Widget     WI_athena_logo = NULL; /* deferred creation */
Widget     WI_athena_scroll_bar = NULL; /* deferred creation */
Widget     WI_athena_strip_chart = NULL; /* deferred creation */
Widget     WI_athena_popup_a_menu = NULL; /* deferred creation */
Widget     WI_athena_simple_menu = NULL; /* deferred creation */
Widget     WI_athena_viewport = NULL; /* deferred creation */
Widget      WI_v1 = NULL; /* deferred creation */
Widget       WI_v2 = NULL; /* deferred creation */
Widget     WI_athena_viewport_label = NULL; /* deferred creation */
Widget     WI_athena_current_class = NULL; /* deferred creation */
Widget     WI_athena_mailbox_label = NULL; /* deferred creation */
Widget     WI_athena_stripchart_label = NULL; /* deferred creation */
Widget   WI_widget_layout_shell = NULL; /* deferred creation */
Widget    WI_widget_layout = NULL; /* deferred creation */
Widget     WI_widget_entry_label = NULL; /* deferred creation */
Widget     WI_widget_hide = NULL; /* deferred creation */
Widget     WI_widget_entry = NULL; /* deferred creation */
Widget     WI_widget_resources_label = NULL; /* deferred creation */
Widget     WI_widget_resources_viewport = NULL; /* deferred creation */
Widget   WI_busy_window;


/* RUNTIME BINDING STRUCTURE */

struct w_bind_list {
	Widget *w;
	String str;
};

struct w_bind_list WI_dirt_bind_list[] = {
	{ &WI_main_layout, "*mainLayout" },
	{ &WI_main_title, "*mainTitle" },
	{ &WI_main_menu, "*mainMenu" },
	{ &WI_create_pressup, "*createPressup" },
	{ &WI_create_shell, "*createShell" },
	{ &WI_create_layout, "*createLayout" },
	{ &WI_create_hide, "*createHide" },
	{ &WI_create_name_label, "*createNameLabel" },
	{ &WI_create_name_entry, "*createNameEntry" },
	{ &WI_create_class_label, "*createClassLabel" },
	{ &WI_create_class_entry, "*createClassEntry" },
	{ &WI_app_x_locked_toggle, "*appXLockedToggle" },
	{ &WI_app_x_pos_value, "*appXPosValue" },
	{ &WI_app_y_locked_toggle, "*appYLockedToggle" },
	{ &WI_app_y_pos_value, "*appYPosValue" },
	{ &WI_app_width_locked_toggle, "*appWidthLockedToggle" },
	{ &WI_app_width_value, "*appWidthValue" },
	{ &WI_app_height_locked_toggle, "*appHeightLockedToggle" },
	{ &WI_app_height_value, "*appHeightValue" },
	{ &WI_app_border_label, "*appBorderLabel" },
	{ &WI_app_border_value, "*appBorderValue" },
	{ &WI_app_new, "*appNew" },
	{ &WI_app_delete, "*appDelete" },
	{ &WI_app_resources_title, "*appResourcesTitle" },
	{ &WI_app_resources_viewport, "*appResourcesViewport" },
	{ &WI_app_comments, "*appComments" },
	{ &WI_app_blank, "*appBlank" },
	{ &WI_create_title, "*createTitle" },
	{ &WI_new_pressup, "*newPressup" },
	{ &WI_new_shell, "*newShell" },
	{ &WI_new_layout, "*newLayout" },
	{ &WI_new_hide, "*newHide" },
	{ &WI_new_name_label, "*newNameLabel" },
	{ &WI_new_name_entry, "*newNameEntry" },
	{ &WI_new_class_label, "*newClassLabel" },
	{ &WI_new_class_entry, "*newClassEntry" },
	{ &WI_new_parent_label, "*newParentLabel" },
	{ &WI_new_parent_entry, "*newParentEntry" },
	{ &WI_pick_parent, "*pickParent" },
	{ &WI_new_x_pos_label, "*newXPosLabel" },
	{ &WI_new_x_pos_value, "*newXPosValue" },
	{ &WI_new_y_pos_label, "*newYPosLabel" },
	{ &WI_new_y_pos_value, "*newYPosValue" },
	{ &WI_new_width_label, "*newWidthLabel" },
	{ &WI_new_width_value, "*newWidthValue" },
	{ &WI_new_height_label, "*newHeightLabel" },
	{ &WI_new_height_value, "*newHeightValue" },
	{ &WI_new_border_label, "*newBorderLabel" },
	{ &WI_new_border_value, "*newBorderValue" },
	{ &WI_new_managed, "*newManaged" },
	{ &WI_new_pane, "*newPane" },
	{ &WI_class_layout, "*classLayout" },
	{ &WI_class_title, "*classTitle" },
	{ &WI_class_examples, "*classExamples" },
	{ &WI_class_list, "*classList" },
	{ &WI_new_resources_layout, "*newResourcesLayout" },
	{ &WI_new_resources_title, "*newResourcesTitle" },
	{ &WI_new_resources_viewport, "*newResourcesViewport" },
	{ &WI_new_title, "*newTitle" },
	{ &WI_new_create, "*newCreate" },
	{ &WI_new_delete, "*newDelete" },
	{ &WI_new_deferred, "*newDeferred" },
	{ &WI_instance_pressup, "*instancePressup" },
	{ &WI_instance_shell, "*instanceShell" },
	{ &WI_instance_layout, "*instanceLayout" },
	{ &WI_instance_hide, "*instanceHide" },
	{ &WI_instance_name_label, "*instanceNameLabel" },
	{ &WI_instance_name_entry, "*instanceNameEntry" },
	{ &WI_instance_class_label, "*instanceClassLabel" },
	{ &WI_instance_class_entry, "*instanceClassEntry" },
	{ &WI_instance_parent_label, "*instanceParentLabel" },
	{ &WI_instance_parent_entry, "*instanceParentEntry" },
	{ &WI_x_pos_label, "*xPosLabel" },
	{ &WI_x_pos_value, "*xPosValue" },
	{ &WI_y_pos_label, "*yPosLabel" },
	{ &WI_y_pos_value, "*yPosValue" },
	{ &WI_width_label, "*widthLabel" },
	{ &WI_width_value, "*widthValue" },
	{ &WI_height_label, "*heightLabel" },
	{ &WI_height_value, "*heightValue" },
	{ &WI_border_label, "*borderLabel" },
	{ &WI_border_value, "*borderValue" },
	{ &WI_instance_managed, "*instanceManaged" },
	{ &WI_instance_resources_title, "*instanceResourcesTitle" },
	{ &WI_instance_resources_viewport, "*instanceResourcesViewport" },
	{ &WI_edit_comments, "*editComments" },
	{ &WI_instance_title, "*instanceTitle" },
	{ &WI_instance_deferred, "*instanceDeferred" },
	{ &WI_instance_list_title, "*instanceListTitle" },
	{ &WI_instance_list, "*instanceList" },
	{ &WI_action_stubs_pressup, "*actionStubsPressup" },
	{ &WI_action_stubs_shell, "*actionStubsShell" },
	{ &WI_action_stubs_layout, "*actionStubsLayout" },
	{ &WI_action_stubs_hide, "*actionStubsHide" },
	{ &WI_action_stubs_label, "*actionStubsLabel" },
	{ &WI_action_stubs_entry, "*actionStubsEntry" },
	{ &WI_action_stubs_list_label, "*actionStubsListLabel" },
	{ &WI_action_stubs_list, "*actionStubsList" },
	{ &WI_action_stubs_register, "*actionStubsRegister" },
	{ &WI_action_stubs_title, "*actionStubsTitle" },
	{ &WI_callback_stubs_pressup, "*callbackStubsPressup" },
	{ &WI_callback_stubs_shell, "*callbackStubsShell" },
	{ &WI_callback_stubs_layout, "*callbackStubsLayout" },
	{ &WI_callback_stubs_hide, "*callbackStubsHide" },
	{ &WI_callback_stubs_register, "*callbackStubsRegister" },
	{ &WI_callback_stubs_label, "*callbackStubsLabel" },
	{ &WI_callback_stubs_entry, "*callbackStubsEntry" },
	{ &WI_callback_stubs_list_label, "*callbackStubsListLabel" },
	{ &WI_callback_stubs_list, "*callbackStubsList" },
	{ &WI_callback_stubs_title, "*callbackStubsTitle" },
	{ &WI_trans_shell, "*transShell" },
	{ &WI_translations_layout, "*translationsLayout" },
	{ &WI_trans_apply_button, "*transApplyButton" },
	{ &WI_trans_hide_button, "*transHideButton" },
	{ &WI_events_label, "*eventsLabel" },
	{ &WI_actions_label, "*actionsLabel" },
	{ &WI_trans_title, "*transTitle" },
	{ &WI_events_view, "*eventsView" },
	{ &WI_current_translations, "*currentTranslations" },
	{ &WI_actions_view, "*actionsView" },
	{ &WI_trans_v_pane, "*transVPane" },
	{ &WI_trans_text, "*transText" },
	{ &WI_trans_error, "*transError" },
	{ &WI_error_shell, "*errorShell" },
	{ &WI_error_trap, "*errorTrap" },
	{ &WI_delete_dialog_shell, "*deleteDialogShell" },
	{ &WI_delete_dialog_layout, "*deleteDialogLayout" },
	{ &WI_delete_dialog_title, "*deleteDialogTitle" },
	{ &WI_delete_dialog_object, "*deleteDialogObject" },
	{ &WI_delete_dialog_yes, "*deleteDialogYes" },
	{ &WI_delete_dialog_no, "*deleteDialogNo" },
	{ &WI_file_dialog_shell, "*fileDialogShell" },
	{ &WI_file_dialog_layout, "*fileDialogLayout" },
	{ &WI_file_dialog_title, "*fileDialogTitle" },
	{ &WI_file_dialog_spec_prefix, "*fileDialogSpecPrefix" },
	{ &WI_file_dialog_spec_label, "*fileDialogSpecLabel" },
	{ &WI_file_dialog_save_spec, "*fileDialogSaveSpec" },
	{ &WI_file_dialog_save_code, "*fileDialogSaveCode" },
	{ &WI_file_dialog_save_both, "*fileDialogSaveBoth" },
	{ &WI_file_dialog_save_cancel, "*fileDialogSaveCancel" },
	{ &WI_file_dialog_code_prefix, "*fileDialogCodePrefix" },
	{ &WI_file_dialog_code_label, "*fileDialogCodeLabel" },
	{ &WI_file_dialog_save_resources, "*fileDialogSaveResources" },
	{ &WI_templates_pressup, "*templatesPressup" },
	{ &WI_templates_shell, "*templatesShell" },
	{ &WI_templates_pane, "*templatesPane" },
	{ &WI_templates_layout, "*templatesLayout" },
	{ &WI_templates_hide, "*templatesHide" },
	{ &WI_templates_name, "*templatesName" },
	{ &WI_templates_name_entry, "*templatesNameEntry" },
	{ &WI_templates_notes_title, "*templatesNotesTitle" },
	{ &WI_templates_notes, "*templatesNotes" },
	{ &WI_templates_title, "*templatesTitle" },
	{ &WI_template_create, "*templateCreate" },
	{ &WI_templates_avail_layout, "*templatesAvailLayout" },
	{ &WI_templates_avail_title, "*templatesAvailTitle" },
	{ &WI_templates_available, "*templatesAvailable" },
	{ &WI_templates_heir_layout, "*templatesHeirLayout" },
	{ &WI_templates_heir_title, "*templatesHeirTitle" },
	{ &WI_templates_heirarchy, "*templatesHeirarchy" },
	{ &WI_comment_shell, "*commentShell" },
	{ &WI_comment_pane, "*commentPane" },
	{ &WI_comment_layout, "*commentLayout" },
	{ &WI_comment_title, "*commentTitle" },
	{ &WI_comment_hide, "*commentHide" },
	{ &WI_comment_text, "*commentText" },
	{ &WI_help_layout, "*helpLayout" },
	{ &WI_help_title, "*helpTitle" },
	{ &WI_help_text, "*helpText" },
	{ &WI_load_dialog_shell, "*loadDialogShell" },
	{ &WI_load_dialog_layout, "*loadDialogLayout" },
	{ &WI_load_dialog_title, "*loadDialogTitle" },
	{ &WI_load_dialog_prefix_label, "*loadDialogPrefixLabel" },
	{ &WI_load_dialog_spec_prefix, "*loadDialogSpecPrefix" },
	{ &WI_load_dialog_load, "*loadDialogLoad" },
	{ &WI_load_dialog_cancel, "*loadDialogCancel" },
	{ &WI_help_shell, "*helpShell" },
	{ &WI_context_help_layout, "*contextHelpLayout" },
	{ &WI_context_help_title, "*contextHelpTitle" },
	{ &WI_context_help_hide, "*contextHelpHide" },
	{ &WI_help_resource_title, "*helpResourceTitle" },
	{ &WI_help_pane, "*helpPane" },
	{ &WI_help_resource_layout, "*helpResourceLayout" },
	{ &WI_help_resource_label, "*helpResourceLabel" },
	{ &WI_help_resource_text, "*helpResourceText" },
	{ &WI_help_type_layout, "*helpTypeLayout" },
	{ &WI_help_type_text, "*helpTypeText" },
	{ &WI_help_type_label, "*helpTypeLabel" },
	{ &WI_help_class_layout, "*helpClassLayout" },
	{ &WI_help_class_label, "*helpClassLabel" },
	{ &WI_help_class_text, "*helpClassText" },
	{ &WI_busy_window, "*busyWindow" },
};


/* CALLBACK REGISTRATION LIST */

String WI_dirt_callback_names[] = {
	"positionShell",
	"popupShell",
	"SelectClass",
	"SaveUI",
	"ResetCreateObject",
	"RegisterCallback",
	"RegisterAction",
	"PickInstance",
	"PasteEvent",
	"PasteAction",
	"LoadTemplate",
	"LoadSpec",
	"DeleteObject",
	"DeleteApplication",
	"CreateTemplate",
	"CreateObject",
	"CreateApplication",
	"ApplyTranslations",
};

/* ACTION REGISTRATION LIST */

String WI_dirt_action_names[] = {
	"dirtACTUpdateParent",
	"dirtACTUpdateNewName",
	"dirtACTUpdateInstanceName",
	"dirtACTUpdateApplicationName",
	"dirtACTUpdateApplicationClass",
	"dirtACTSaveUI",
	"dirtACTRegisterCallback",
	"dirtACTRegisterAction",
	"dirtACTLoadSpec",
	"dirtACTCreateTemplate",
};


/* LAYOUT CONNECTIONS */

/* widget connection list for UKCLayout widgets */
struct w_connections WI_dirt_widget_connections[] = {
	{ &WI_athena_examples_layout, &WI_athena_examples_title, &WI_athena_examples_layout, vertical_above },
	{ &WI_athena_examples_layout, &WI_athena_current_class, &WI_athena_examples_layout, vertical_above },
	{ &WI_athena_examples_layout, &WI_athena_examples_title, &WI_athena_examples_layout, horizontal_before },
	{ &WI_athena_examples_layout, &WI_athena_examples_title, &WI_athena_current_class, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_current_class, &WI_athena_examples_hide, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_examples_hide, &WI_athena_examples_layout, vertical_above },
	{ &WI_athena_examples_layout, &WI_athena_examples_hide, &WI_athena_logo, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_logo, &WI_athena_scroll_bar, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_editable_text, &WI_athena_logo, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_editable_text, &WI_athena_current_class, vertical_above },
	{ &WI_athena_examples_layout, &WI_athena_examples_box_label, &WI_athena_examples_title, vertical_above },
	{ &WI_athena_examples_layout, &WI_athena_examples_box_label, &WI_athena_box, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_examples_box_label, &WI_athena_examples_layout, horizontal_before },
	{ &WI_athena_examples_layout, &WI_athena_examples_box_label, &WI_athena_editable_text, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_box, &WI_athena_editable_text, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_form_label, &WI_athena_editable_text, vertical_above },
	{ &WI_athena_examples_layout, &WI_athena_box, &WI_athena_form_label, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_box, &WI_athena_examples_layout, horizontal_before },
	{ &WI_athena_examples_layout, &WI_athena_form, &WI_athena_box, horizontal_before },
	{ &WI_athena_examples_layout, &WI_athena_form_label, &WI_athena_form, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_form_label, &WI_athena_logo, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_form, &WI_athena_scroll_bar, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_toggle_label, &WI_athena_scroll_bar, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_toggle, &WI_athena_label, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_label, &WI_athena_scroll_bar, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_toggle, &WI_athena_paned_label, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_toggle_label, &WI_athena_form, vertical_above },
	{ &WI_athena_examples_layout, &WI_athena_label, &WI_athena_form, vertical_above },
	{ &WI_athena_examples_layout, &WI_athena_paned_label, &WI_athena_grip_label, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_paned_label, &WI_athena_popup_a_menu, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_grip_label, &WI_athena_mailbox, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_grip_label, &WI_athena_strip_chart, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_label, &WI_athena_grip, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_grip, &WI_athena_strip_chart, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_mailbox, &WI_athena_mailbox_label, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_strip_chart, &WI_athena_stripchart_label, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_mailbox_label, &WI_athena_stripchart_label, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_mailbox, &WI_athena_strip_chart, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_grip_label, &WI_athena_grip, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_grip, &WI_athena_scroll_bar, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_strip_chart, &WI_athena_scroll_bar, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_stripchart_label, &WI_athena_scroll_bar, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_toggle_label, &WI_athena_toggle, vertical_below },
	{ &WI_athena_examples_layout, &WI_athena_popup_a_menu, &WI_athena_mailbox, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_popup_a_menu, &WI_athena_examples_layout, horizontal_before },
	{ &WI_athena_examples_layout, &WI_athena_grip_label, &WI_athena_label, vertical_above },
	{ &WI_athena_examples_layout, &WI_athena_viewport, &WI_athena_popup_a_menu, vertical_above },
	{ &WI_athena_examples_layout, &WI_athena_viewport_label, &WI_athena_viewport, vertical_above },
	{ &WI_athena_examples_layout, &WI_athena_viewport, &WI_athena_mailbox, horizontal_after },
	{ &WI_athena_examples_layout, &WI_athena_viewport, &WI_athena_mailbox_label, horizontal_after },
	{ &WI_main_layout, &WI_main_title, &WI_main_menu, vertical_below },
	{ &WI_main_layout, &WI_main_menu, &WI_instance_list_title, vertical_below },
	{ &WI_main_layout, &WI_instance_list_title, &WI_instance_list, vertical_below },
	{ &WI_main_layout, &WI_instance_list, &WI_create_pressup, vertical_below },
	{ &WI_main_layout, &WI_create_pressup, &WI_new_pressup, vertical_below },
	{ &WI_main_layout, &WI_new_pressup, &WI_instance_pressup, vertical_below },
	{ &WI_main_layout, &WI_templates_pressup, &WI_action_stubs_pressup, vertical_below },
	{ &WI_main_layout, &WI_action_stubs_pressup, &WI_callback_stubs_pressup, vertical_below },
	{ &WI_main_layout, &WI_main_title, &WI_main_layout, vertical_above },
	{ &WI_main_layout, &WI_main_title, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_main_menu, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_instance_list_title, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_instance_list, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_create_pressup, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_new_pressup, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_instance_pressup, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_templates_pressup, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_action_stubs_pressup, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_callback_stubs_pressup, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_instance_pressup, &WI_templates_pressup, vertical_below },
	{ &WI_template_building_layout, &WI_template_building_hide, &WI_template_building_layout, vertical_above },
	{ &WI_template_building_layout, &WI_template_building_title, &WI_template_building_area, vertical_below },
	{ &WI_template_building_layout, &WI_template_building_title, &WI_template_building_layout, vertical_above },
	{ &WI_template_building_layout, &WI_template_building_area, &WI_template_building_layout, horizontal_before },
	{ &WI_template_building_layout, &WI_template_building_title, &WI_template_building_layout, horizontal_before },
	{ &WI_template_building_layout, &WI_template_building_hide, &WI_template_building_area, vertical_below },
	{ &WI_templates_heir_layout, &WI_templates_heir_title, &WI_templates_heir_layout, vertical_above },
	{ &WI_templates_heir_layout, &WI_templates_heir_title, &WI_templates_heirarchy, vertical_below },
	{ &WI_templates_heir_layout, &WI_templates_heir_title, &WI_templates_heir_layout, horizontal_before },
	{ &WI_templates_heir_layout, &WI_templates_heirarchy, &WI_templates_heir_layout, horizontal_before },
	{ &WI_templates_avail_layout, &WI_templates_available, &WI_templates_avail_title, vertical_above },
	{ &WI_templates_avail_layout, &WI_templates_avail_title, &WI_templates_avail_layout, vertical_above },
	{ &WI_templates_avail_layout, &WI_templates_available, &WI_templates_avail_layout, horizontal_before },
	{ &WI_templates_avail_layout, &WI_templates_avail_title, &WI_templates_avail_layout, horizontal_before },
	{ &WI_templates_layout, &WI_templates_notes_title, &WI_templates_notes, vertical_below },
	{ &WI_templates_layout, &WI_templates_notes_title, &WI_templates_layout, horizontal_before },
	{ &WI_templates_layout, &WI_templates_notes, &WI_templates_layout, horizontal_before },
	{ &WI_templates_layout, &WI_templates_hide, &WI_templates_layout, vertical_above },
	{ &WI_instance_layout, &WI_instance_hide, &WI_instance_layout, vertical_above },
	{ &WI_create_layout, &WI_create_hide, &WI_app_delete, vertical_below },
	{ &WI_create_layout, &WI_app_delete, &WI_create_name_entry, vertical_below },
	{ &WI_create_layout, &WI_create_name_entry, &WI_create_class_entry, vertical_below },
	{ &WI_create_layout, &WI_create_class_entry, &WI_app_y_pos_value, vertical_below },
	{ &WI_create_layout, &WI_app_y_locked_toggle, &WI_app_height_locked_toggle, vertical_below },
	{ &WI_create_layout, &WI_app_y_pos_value, &WI_app_height_value, vertical_below },
	{ &WI_create_layout, &WI_app_height_value, &WI_app_comments, vertical_below },
	{ &WI_create_layout, &WI_app_comments, &WI_app_resources_title, vertical_below },
	{ &WI_create_layout, &WI_app_border_value, &WI_app_resources_title, vertical_below },
	{ &WI_create_layout, &WI_app_new, &WI_create_name_entry, vertical_below },
	{ &WI_create_layout, &WI_create_name_label, &WI_create_class_label, vertical_below },
	{ &WI_create_layout, &WI_create_class_label, &WI_app_x_locked_toggle, vertical_below },
	{ &WI_create_layout, &WI_app_x_locked_toggle, &WI_app_width_locked_toggle, vertical_below },
	{ &WI_create_layout, &WI_app_width_locked_toggle, &WI_app_border_label, vertical_below },
	{ &WI_create_layout, &WI_app_border_label, &WI_app_resources_title, vertical_below },
	{ &WI_create_layout, &WI_app_resources_title, &WI_app_resources_viewport, vertical_below },
	{ &WI_create_layout, &WI_app_width_value, &WI_app_border_value, vertical_below },
	{ &WI_create_layout, &WI_app_x_pos_value, &WI_app_width_value, vertical_below },
	{ &WI_create_layout, &WI_create_name_label, &WI_create_name_entry, horizontal_after },
	{ &WI_create_layout, &WI_create_class_label, &WI_create_class_entry, horizontal_after },
	{ &WI_create_layout, &WI_create_name_label, &WI_create_layout, horizontal_before },
	{ &WI_create_layout, &WI_create_class_label, &WI_create_layout, horizontal_before },
	{ &WI_create_layout, &WI_app_x_locked_toggle, &WI_create_layout, horizontal_before },
	{ &WI_create_layout, &WI_app_x_pos_value, &WI_app_x_locked_toggle, horizontal_before },
	{ &WI_create_layout, &WI_app_x_pos_value, &WI_app_y_locked_toggle, horizontal_after },
	{ &WI_create_layout, &WI_app_y_locked_toggle, &WI_app_y_pos_value, horizontal_after },
	{ &WI_create_layout, &WI_app_height_locked_toggle, &WI_app_height_value, horizontal_after },
	{ &WI_create_layout, &WI_app_border_value, &WI_app_border_label, horizontal_before },
	{ &WI_create_layout, &WI_app_width_value, &WI_app_width_locked_toggle, horizontal_before },
	{ &WI_create_layout, &WI_app_width_value, &WI_app_height_locked_toggle, horizontal_after },
	{ &WI_create_layout, &WI_app_width_locked_toggle, &WI_create_layout, horizontal_before },
	{ &WI_create_layout, &WI_app_border_label, &WI_create_layout, horizontal_before },
	{ &WI_create_layout, &WI_app_resources_title, &WI_create_layout, horizontal_before },
	{ &WI_create_layout, &WI_app_resources_viewport, &WI_create_layout, horizontal_before },
	{ &WI_create_layout, &WI_create_hide, &WI_create_layout, vertical_above },
	{ &WI_file_dialog_layout, &WI_file_dialog_title, &WI_file_dialog_spec_prefix, vertical_below },
	{ &WI_file_dialog_layout, &WI_file_dialog_title, &WI_file_dialog_spec_label, vertical_below },
	{ &WI_file_dialog_layout, &WI_file_dialog_spec_label, &WI_file_dialog_code_label, vertical_below },
	{ &WI_file_dialog_layout, &WI_file_dialog_code_label, &WI_file_dialog_code_prefix, horizontal_after },
	{ &WI_file_dialog_layout, &WI_file_dialog_spec_label, &WI_file_dialog_spec_prefix, horizontal_after },
	{ &WI_file_dialog_layout, &WI_file_dialog_code_label, &WI_file_dialog_save_spec, vertical_below },
	{ &WI_file_dialog_layout, &WI_file_dialog_code_prefix, &WI_file_dialog_save_code, vertical_below },
	{ &WI_file_dialog_layout, &WI_file_dialog_spec_prefix, &WI_file_dialog_code_prefix, vertical_below },
	{ &WI_file_dialog_layout, &WI_file_dialog_save_code, &WI_file_dialog_save_cancel, vertical_below },
	{ &WI_file_dialog_layout, &WI_file_dialog_save_spec, &WI_file_dialog_save_both, vertical_below },
	{ &WI_file_dialog_layout, &WI_file_dialog_save_spec, &WI_file_dialog_save_code, horizontal_after },
	{ &WI_file_dialog_layout, &WI_file_dialog_save_both, &WI_file_dialog_save_cancel, horizontal_after },
	{ &WI_file_dialog_layout, &WI_file_dialog_layout, &WI_file_dialog_save_spec, horizontal_after },
	{ &WI_file_dialog_layout, &WI_file_dialog_layout, &WI_file_dialog_save_both, horizontal_after },
	{ &WI_file_dialog_layout, &WI_file_dialog_code_label, &WI_file_dialog_layout, horizontal_before },
	{ &WI_file_dialog_layout, &WI_file_dialog_spec_label, &WI_file_dialog_layout, horizontal_before },
	{ &WI_file_dialog_layout, &WI_file_dialog_title, &WI_file_dialog_layout, horizontal_before },
	{ &WI_file_dialog_layout, &WI_file_dialog_title, &WI_file_dialog_layout, vertical_above },
	{ &WI_delete_dialog_layout, &WI_delete_dialog_title, &WI_delete_dialog_object, vertical_below },
	{ &WI_delete_dialog_layout, &WI_delete_dialog_object, &WI_delete_dialog_yes, vertical_below },
	{ &WI_delete_dialog_layout, &WI_delete_dialog_object, &WI_delete_dialog_no, vertical_below },
	{ &WI_delete_dialog_layout, &WI_delete_dialog_no, &WI_delete_dialog_yes, horizontal_before },
	{ &WI_delete_dialog_layout, &WI_delete_dialog_yes, &WI_delete_dialog_layout, horizontal_before },
	{ &WI_delete_dialog_layout, &WI_delete_dialog_title, &WI_delete_dialog_layout, horizontal_before },
	{ &WI_delete_dialog_layout, &WI_delete_dialog_object, &WI_delete_dialog_layout, horizontal_before },
	{ &WI_delete_dialog_layout, &WI_delete_dialog_title, &WI_delete_dialog_layout, vertical_above },
	{ &WI_translations_layout, &WI_trans_title, &WI_current_translations, vertical_below },
	{ &WI_translations_layout, &WI_translations_layout, &WI_trans_hide_button, vertical_below },
	{ &WI_translations_layout, &WI_trans_hide_button, &WI_actions_label, vertical_below },
	{ &WI_translations_layout, &WI_actions_label, &WI_actions_view, vertical_below },
	{ &WI_translations_layout, &WI_translations_layout, &WI_trans_title, vertical_below },
	{ &WI_translations_layout, &WI_current_translations, &WI_trans_v_pane, vertical_below },
	{ &WI_translations_layout, &WI_events_label, &WI_events_view, vertical_below },
	{ &WI_translations_layout, &WI_trans_apply_button, &WI_events_label, vertical_below },
	{ &WI_translations_layout, &WI_translations_layout, &WI_trans_apply_button, vertical_below },
	{ &WI_translations_layout, &WI_translations_layout, &WI_trans_apply_button, horizontal_after },
	{ &WI_translations_layout, &WI_trans_apply_button, &WI_trans_title, horizontal_after },
	{ &WI_translations_layout, &WI_trans_title, &WI_trans_hide_button, horizontal_after },
	{ &WI_translations_layout, &WI_actions_label, &WI_current_translations, horizontal_before },
	{ &WI_translations_layout, &WI_current_translations, &WI_events_label, horizontal_before },
	{ &WI_translations_layout, &WI_events_label, &WI_translations_layout, horizontal_before },
	{ &WI_translations_layout, &WI_translations_layout, &WI_events_view, horizontal_after },
	{ &WI_translations_layout, &WI_events_view, &WI_trans_v_pane, horizontal_after },
	{ &WI_translations_layout, &WI_trans_v_pane, &WI_actions_view, horizontal_after },
	{ &WI_create_layout, &WI_app_border_value, &WI_app_blank, horizontal_after },
	{ &WI_create_layout, &WI_app_blank, &WI_app_comments, horizontal_after },
	{ &WI_create_layout, &WI_app_blank, &WI_app_resources_title, vertical_below },
	{ &WI_create_layout, &WI_app_height_locked_toggle, &WI_app_blank, vertical_below },
	{ &WI_templates_layout, &WI_templates_name, &WI_templates_name_entry, horizontal_after },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_hide, &WI_callback_stubs_register, vertical_below },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_register, &WI_callback_stubs_entry, vertical_below },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_entry, &WI_callback_stubs_list_label, vertical_below },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_list_label, &WI_callback_stubs_list, vertical_below },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_register, &WI_callback_stubs_label, vertical_below },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_label, &WI_callback_stubs_list_label, vertical_below },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_layout, &WI_callback_stubs_register, horizontal_after },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_layout, &WI_callback_stubs_label, horizontal_after },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_label, &WI_callback_stubs_entry, horizontal_after },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_layout, &WI_callback_stubs_list_label, horizontal_after },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_list, &WI_callback_stubs_layout, horizontal_before },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_hide, &WI_callback_stubs_layout, vertical_above },
	{ &WI_action_stubs_layout, &WI_action_stubs_hide, &WI_action_stubs_register, vertical_below },
	{ &WI_action_stubs_layout, &WI_action_stubs_register, &WI_action_stubs_entry, vertical_below },
	{ &WI_action_stubs_layout, &WI_action_stubs_entry, &WI_action_stubs_list_label, vertical_below },
	{ &WI_action_stubs_layout, &WI_action_stubs_list_label, &WI_action_stubs_list, vertical_below },
	{ &WI_action_stubs_layout, &WI_action_stubs_register, &WI_action_stubs_label, vertical_below },
	{ &WI_action_stubs_layout, &WI_action_stubs_label, &WI_action_stubs_list_label, vertical_below },
	{ &WI_action_stubs_layout, &WI_action_stubs_layout, &WI_action_stubs_register, horizontal_after },
	{ &WI_action_stubs_layout, &WI_action_stubs_layout, &WI_action_stubs_label, horizontal_after },
	{ &WI_action_stubs_layout, &WI_action_stubs_layout, &WI_action_stubs_list_label, horizontal_after },
	{ &WI_action_stubs_layout, &WI_action_stubs_layout, &WI_action_stubs_list, horizontal_after },
	{ &WI_action_stubs_layout, &WI_action_stubs_layout, &WI_action_stubs_hide, vertical_below },
	{ &WI_comment_layout, &WI_comment_layout, &WI_comment_title, vertical_below },
	{ &WI_comment_layout, &WI_comment_title, &WI_comment_text, vertical_below },
	{ &WI_comment_layout, &WI_comment_layout, &WI_comment_hide, vertical_below },
	{ &WI_comment_layout, &WI_comment_hide, &WI_comment_text, vertical_below },
	{ &WI_comment_layout, &WI_comment_layout, &WI_comment_title, horizontal_after },
	{ &WI_comment_layout, &WI_comment_title, &WI_comment_hide, horizontal_after },
	{ &WI_comment_layout, &WI_comment_layout, &WI_comment_text, horizontal_after },
	{ &WI_help_layout, &WI_help_layout, &WI_help_title, vertical_below },
	{ &WI_help_layout, &WI_help_title, &WI_help_text, vertical_below },
	{ &WI_help_layout, &WI_help_layout, &WI_help_title, horizontal_after },
	{ &WI_help_layout, &WI_help_layout, &WI_help_text, horizontal_after },
	{ &WI_action_stubs_layout, &WI_action_stubs_label, &WI_action_stubs_entry, horizontal_after },
	{ &WI_load_dialog_layout, &WI_load_dialog_layout, &WI_load_dialog_title, vertical_below },
	{ &WI_load_dialog_layout, &WI_load_dialog_layout, &WI_load_dialog_title, horizontal_after },
	{ &WI_load_dialog_layout, &WI_load_dialog_title, &WI_load_dialog_prefix_label, vertical_below },
	{ &WI_load_dialog_layout, &WI_load_dialog_layout, &WI_load_dialog_prefix_label, horizontal_after },
	{ &WI_load_dialog_layout, &WI_load_dialog_spec_prefix, &WI_load_dialog_cancel, vertical_below },
	{ &WI_load_dialog_layout, &WI_load_dialog_spec_prefix, &WI_load_dialog_load, vertical_below },
	{ &WI_load_dialog_layout, &WI_load_dialog_prefix_label, &WI_load_dialog_load, vertical_below },
	{ &WI_load_dialog_layout, &WI_load_dialog_title, &WI_load_dialog_spec_prefix, vertical_below },
	{ &WI_load_dialog_layout, &WI_load_dialog_prefix_label, &WI_load_dialog_spec_prefix, horizontal_after },
	{ &WI_load_dialog_layout, &WI_load_dialog_layout, &WI_load_dialog_load, horizontal_after },
	{ &WI_load_dialog_layout, &WI_load_dialog_load, &WI_load_dialog_cancel, horizontal_after },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_layout, &WI_callback_stubs_title, vertical_below },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_title, &WI_callback_stubs_layout, horizontal_before },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_title, &WI_callback_stubs_hide, horizontal_after },
	{ &WI_callback_stubs_layout, &WI_callback_stubs_title, &WI_callback_stubs_register, vertical_below },
	{ &WI_action_stubs_layout, &WI_action_stubs_title, &WI_action_stubs_register, vertical_below },
	{ &WI_action_stubs_layout, &WI_action_stubs_title, &WI_action_stubs_layout, vertical_above },
	{ &WI_create_layout, &WI_create_title, &WI_create_hide, horizontal_after },
	{ &WI_create_layout, &WI_create_title, &WI_create_layout, horizontal_before },
	{ &WI_create_layout, &WI_create_title, &WI_create_layout, vertical_above },
	{ &WI_create_layout, &WI_create_title, &WI_app_delete, vertical_below },
	{ &WI_templates_layout, &WI_templates_title, &WI_templates_hide, horizontal_after },
	{ &WI_templates_layout, &WI_templates_hide, &WI_template_create, vertical_below },
	{ &WI_templates_layout, &WI_templates_title, &WI_template_create, vertical_below },
	{ &WI_templates_layout, &WI_templates_layout, &WI_template_create, horizontal_after },
	{ &WI_templates_layout, &WI_template_create, &WI_templates_name_entry, vertical_below },
	{ &WI_templates_layout, &WI_templates_layout, &WI_templates_name, horizontal_after },
	{ &WI_templates_layout, &WI_template_create, &WI_templates_name, vertical_below },
	{ &WI_templates_layout, &WI_templates_name, &WI_templates_notes_title, vertical_below },
	{ &WI_templates_layout, &WI_templates_name_entry, &WI_templates_notes_title, vertical_below },
	{ &WI_templates_layout, &WI_templates_layout, &WI_templates_title, vertical_below },
	{ &WI_templates_layout, &WI_templates_layout, &WI_templates_title, horizontal_after },
	{ &WI_instance_layout, &WI_instance_hide, &WI_instance_name_entry, vertical_below },
	{ &WI_instance_layout, &WI_instance_name_entry, &WI_instance_class_entry, vertical_below },
	{ &WI_instance_layout, &WI_instance_class_entry, &WI_instance_parent_entry, vertical_below },
	{ &WI_instance_layout, &WI_instance_parent_entry, &WI_y_pos_value, vertical_below },
	{ &WI_instance_layout, &WI_y_pos_value, &WI_height_value, vertical_below },
	{ &WI_instance_layout, &WI_height_label, &WI_instance_managed, vertical_below },
	{ &WI_instance_layout, &WI_instance_managed, &WI_instance_resources_title, vertical_below },
	{ &WI_instance_layout, &WI_instance_resources_title, &WI_instance_resources_viewport, vertical_below },
	{ &WI_instance_layout, &WI_border_value, &WI_instance_resources_title, vertical_below },
	{ &WI_instance_layout, &WI_border_label, &WI_instance_resources_title, vertical_below },
	{ &WI_instance_layout, &WI_width_label, &WI_border_label, vertical_below },
	{ &WI_instance_layout, &WI_width_value, &WI_border_value, vertical_below },
	{ &WI_instance_layout, &WI_y_pos_label, &WI_height_label, vertical_below },
	{ &WI_instance_layout, &WI_instance_parent_entry, &WI_y_pos_label, vertical_below },
	{ &WI_instance_layout, &WI_instance_title, &WI_instance_name_entry, vertical_below },
	{ &WI_instance_layout, &WI_instance_name_label, &WI_instance_class_label, vertical_below },
	{ &WI_instance_layout, &WI_instance_class_label, &WI_instance_parent_label, vertical_below },
	{ &WI_instance_layout, &WI_instance_parent_label, &WI_x_pos_label, vertical_below },
	{ &WI_instance_layout, &WI_x_pos_label, &WI_width_label, vertical_below },
	{ &WI_instance_layout, &WI_instance_parent_entry, &WI_x_pos_value, vertical_below },
	{ &WI_instance_layout, &WI_instance_name_entry, &WI_instance_name_label, horizontal_before },
	{ &WI_instance_layout, &WI_instance_class_label, &WI_instance_class_entry, horizontal_after },
	{ &WI_instance_layout, &WI_instance_parent_label, &WI_instance_parent_entry, horizontal_after },
	{ &WI_instance_layout, &WI_x_pos_value, &WI_y_pos_label, horizontal_after },
	{ &WI_instance_layout, &WI_y_pos_label, &WI_y_pos_value, horizontal_after },
	{ &WI_instance_layout, &WI_x_pos_label, &WI_x_pos_value, horizontal_after },
	{ &WI_instance_layout, &WI_instance_name_label, &WI_instance_layout, horizontal_before },
	{ &WI_instance_layout, &WI_instance_class_label, &WI_instance_layout, horizontal_before },
	{ &WI_instance_layout, &WI_instance_parent_label, &WI_instance_layout, horizontal_before },
	{ &WI_instance_layout, &WI_x_pos_label, &WI_instance_layout, horizontal_before },
	{ &WI_instance_layout, &WI_width_label, &WI_instance_layout, horizontal_before },
	{ &WI_instance_layout, &WI_border_label, &WI_instance_layout, horizontal_before },
	{ &WI_instance_layout, &WI_instance_resources_title, &WI_instance_layout, horizontal_before },
	{ &WI_instance_layout, &WI_instance_resources_viewport, &WI_instance_layout, horizontal_before },
	{ &WI_instance_layout, &WI_x_pos_value, &WI_width_value, vertical_below },
	{ &WI_instance_layout, &WI_width_label, &WI_width_value, horizontal_after },
	{ &WI_instance_layout, &WI_width_value, &WI_height_label, horizontal_after },
	{ &WI_instance_layout, &WI_height_label, &WI_height_value, horizontal_after },
	{ &WI_instance_layout, &WI_border_label, &WI_border_value, horizontal_after },
	{ &WI_instance_layout, &WI_border_value, &WI_instance_managed, horizontal_after },
	{ &WI_instance_layout, &WI_instance_layout, &WI_instance_title, vertical_below },
	{ &WI_instance_layout, &WI_instance_layout, &WI_instance_title, horizontal_after },
	{ &WI_new_layout, &WI_new_name_label, &WI_new_class_label, vertical_below },
	{ &WI_new_layout, &WI_new_name_entry, &WI_new_class_entry, vertical_below },
	{ &WI_new_layout, &WI_new_class_label, &WI_new_parent_label, vertical_below },
	{ &WI_new_layout, &WI_new_class_entry, &WI_new_parent_entry, vertical_below },
	{ &WI_new_layout, &WI_new_class_entry, &WI_pick_parent, vertical_below },
	{ &WI_new_layout, &WI_pick_parent, &WI_new_y_pos_value, vertical_below },
	{ &WI_new_layout, &WI_new_parent_entry, &WI_new_y_pos_value, vertical_below },
	{ &WI_new_layout, &WI_new_parent_entry, &WI_new_y_pos_label, vertical_below },
	{ &WI_new_layout, &WI_new_parent_entry, &WI_new_x_pos_value, vertical_below },
	{ &WI_new_layout, &WI_new_parent_label, &WI_new_x_pos_label, vertical_below },
	{ &WI_new_layout, &WI_new_x_pos_label, &WI_new_width_label, vertical_below },
	{ &WI_new_layout, &WI_new_x_pos_value, &WI_new_width_value, vertical_below },
	{ &WI_new_layout, &WI_new_y_pos_label, &WI_new_height_label, vertical_below },
	{ &WI_new_layout, &WI_new_y_pos_value, &WI_new_height_value, vertical_below },
	{ &WI_new_layout, &WI_new_height_value, &WI_new_managed, vertical_below },
	{ &WI_new_layout, &WI_new_height_label, &WI_new_managed, vertical_below },
	{ &WI_new_layout, &WI_new_width_value, &WI_new_border_value, vertical_below },
	{ &WI_new_layout, &WI_new_width_label, &WI_new_border_label, vertical_below },
	{ &WI_new_layout, &WI_new_border_label, &WI_new_pane, vertical_below },
	{ &WI_new_layout, &WI_new_border_value, &WI_new_pane, vertical_below },
	{ &WI_new_layout, &WI_new_managed, &WI_new_pane, vertical_below },
	{ &WI_class_layout, &WI_class_title, &WI_class_list, vertical_below },
	{ &WI_class_layout, &WI_class_examples, &WI_class_list, vertical_below },
	{ &WI_new_resources_layout, &WI_new_resources_title, &WI_new_resources_viewport, vertical_below },
	{ &WI_new_layout, &WI_new_title, &WI_new_hide, horizontal_after },
	{ &WI_new_layout, &WI_new_layout, &WI_new_name_label, horizontal_after },
	{ &WI_new_layout, &WI_new_name_label, &WI_new_name_entry, horizontal_after },
	{ &WI_new_layout, &WI_new_layout, &WI_new_class_label, horizontal_after },
	{ &WI_new_layout, &WI_new_class_label, &WI_new_class_entry, horizontal_after },
	{ &WI_new_layout, &WI_new_layout, &WI_new_parent_label, horizontal_after },
	{ &WI_new_layout, &WI_new_parent_label, &WI_new_parent_entry, horizontal_after },
	{ &WI_new_layout, &WI_new_parent_entry, &WI_pick_parent, horizontal_after },
	{ &WI_new_layout, &WI_new_layout, &WI_new_x_pos_label, horizontal_after },
	{ &WI_new_layout, &WI_new_x_pos_label, &WI_new_x_pos_value, horizontal_after },
	{ &WI_new_layout, &WI_new_x_pos_value, &WI_new_y_pos_label, horizontal_after },
	{ &WI_new_layout, &WI_new_y_pos_label, &WI_new_y_pos_value, horizontal_after },
	{ &WI_new_layout, &WI_new_layout, &WI_new_width_label, horizontal_after },
	{ &WI_new_layout, &WI_new_width_label, &WI_new_width_value, horizontal_after },
	{ &WI_new_layout, &WI_new_width_value, &WI_new_height_label, horizontal_after },
	{ &WI_new_layout, &WI_new_height_label, &WI_new_height_value, horizontal_after },
	{ &WI_new_layout, &WI_new_layout, &WI_new_border_label, horizontal_after },
	{ &WI_new_layout, &WI_new_border_label, &WI_new_border_value, horizontal_after },
	{ &WI_new_layout, &WI_new_border_value, &WI_new_managed, horizontal_after },
	{ &WI_class_layout, &WI_class_title, &WI_class_examples, horizontal_after },
	{ &WI_class_layout, &WI_class_list, &WI_class_layout, horizontal_before },
	{ &WI_class_layout, &WI_class_title, &WI_class_layout, horizontal_before },
	{ &WI_new_resources_layout, &WI_new_resources_viewport, &WI_new_resources_layout, horizontal_before },
	{ &WI_new_resources_layout, &WI_new_resources_title, &WI_new_resources_layout, horizontal_before },
	{ &WI_new_layout, &WI_new_title, &WI_new_layout, vertical_above },
	{ &WI_new_layout, &WI_new_layout, &WI_new_title, horizontal_after },
	{ &WI_class_layout, &WI_class_layout, &WI_class_title, vertical_below },
	{ &WI_class_layout, &WI_class_examples, &WI_class_layout, vertical_above },
	{ &WI_new_resources_layout, &WI_new_resources_title, &WI_new_resources_layout, vertical_above },
	{ &WI_context_help_layout, &WI_context_help_title, &WI_context_help_layout, vertical_above },
	{ &WI_context_help_layout, &WI_context_help_title, &WI_context_help_layout, horizontal_before },
	{ &WI_context_help_layout, &WI_context_help_layout, &WI_context_help_hide, vertical_below },
	{ &WI_context_help_layout, &WI_context_help_hide, &WI_help_resource_title, vertical_below },
	{ &WI_context_help_layout, &WI_context_help_title, &WI_help_resource_title, vertical_below },
	{ &WI_context_help_layout, &WI_context_help_title, &WI_context_help_hide, horizontal_after },
	{ &WI_context_help_layout, &WI_context_help_layout, &WI_help_resource_title, horizontal_after },
	{ &WI_context_help_layout, &WI_help_resource_title, &WI_help_pane, vertical_below },
	{ &WI_context_help_layout, &WI_help_pane, &WI_context_help_layout, horizontal_before },
	{ &WI_help_resource_layout, &WI_help_resource_label, &WI_help_resource_layout, vertical_above },
	{ &WI_help_resource_layout, &WI_help_resource_label, &WI_help_resource_layout, horizontal_before },
	{ &WI_help_resource_layout, &WI_help_resource_text, &WI_help_resource_layout, horizontal_before },
	{ &WI_help_resource_layout, &WI_help_resource_label, &WI_help_resource_text, vertical_below },
	{ &WI_help_type_layout, &WI_help_type_label, &WI_help_type_text, vertical_below },
	{ &WI_help_type_layout, &WI_help_type_label, &WI_help_type_layout, horizontal_before },
	{ &WI_help_type_layout, &WI_help_type_layout, &WI_help_type_label, vertical_below },
	{ &WI_help_type_layout, &WI_help_type_text, &WI_help_type_layout, horizontal_before },
	{ &WI_help_class_layout, &WI_help_class_layout, &WI_help_class_label, vertical_below },
	{ &WI_help_class_layout, &WI_help_class_label, &WI_help_class_layout, horizontal_before },
	{ &WI_help_class_layout, &WI_help_class_label, &WI_help_class_text, vertical_below },
	{ &WI_help_class_layout, &WI_help_class_layout, &WI_help_class_text, horizontal_after },
	{ &WI_instance_layout, &WI_instance_resources_title, &WI_edit_comments, horizontal_after },
	{ &WI_instance_layout, &WI_edit_comments, &WI_instance_resources_viewport, vertical_below },
	{ &WI_instance_layout, &WI_height_value, &WI_instance_deferred, vertical_below },
	{ &WI_instance_layout, &WI_instance_deferred, &WI_edit_comments, vertical_below },
	{ &WI_instance_layout, &WI_instance_deferred, &WI_instance_resources_title, vertical_below },
	{ &WI_instance_layout, &WI_instance_managed, &WI_instance_deferred, horizontal_after },
	{ &WI_new_layout, &WI_new_hide, &WI_new_delete, vertical_below },
	{ &WI_new_layout, &WI_new_title, &WI_new_delete, vertical_below },
	{ &WI_new_layout, &WI_new_title, &WI_new_create, vertical_below },
	{ &WI_new_layout, &WI_new_delete, &WI_new_name_entry, vertical_below },
	{ &WI_new_layout, &WI_new_create, &WI_new_name_entry, vertical_below },
	{ &WI_new_layout, &WI_new_create, &WI_new_name_label, vertical_below },
	{ &WI_new_layout, &WI_new_height_value, &WI_new_deferred, vertical_below },
	{ &WI_new_layout, &WI_new_deferred, &WI_new_pane, vertical_below },
	{ &WI_new_layout, &WI_new_managed, &WI_new_deferred, horizontal_after },
	{ &WI_create_layout, &WI_app_new, &WI_create_name_label, vertical_below },
	{ &WI_create_layout, &WI_create_layout, &WI_app_new, horizontal_after },
	{ &WI_create_layout, &WI_create_title, &WI_app_new, vertical_below },
	{ &WI_instance_layout, &WI_instance_title, &WI_instance_hide, horizontal_after },
	{ &WI_action_stubs_layout, &WI_action_stubs_title, &WI_action_stubs_hide, horizontal_after },
	{ &WI_action_stubs_layout, &WI_action_stubs_layout, &WI_action_stubs_title, horizontal_after },
	{ &WI_new_layout, &WI_new_create, &WI_new_delete, horizontal_after },
	{ &WI_new_layout, &WI_new_layout, &WI_new_create, horizontal_after },
	{ &WI_new_layout, &WI_new_layout, &WI_new_hide, vertical_below },
	{ &WI_new_layout, &WI_new_pane, &WI_new_layout, horizontal_before },
	{ &WI_template_building_layout, &WI_template_building_title, &WI_template_building_hide, horizontal_after },
};

/* END */
#endif /* WI_dirt_layout_h */
