/* SCCSID: @(#)exceptions.h	1.1 (UKC) 5/10/92 */

/* 
 * Copyright 1990 Richard Hesketh / rlh2@ukc.ac.uk
 *                Computing Lab. University of Kent at Canterbury, UK
 *
 * Permission to use, copy, modify and distribute this software and its
 * documentation for any purpose is hereby granted without fee, provided that
 * the above copyright notice appear in all copies and that both that
 * copyright notice and this permission notice appear in supporting
 * documentation, and that the names of Richard Hesketh and The University of
 * Kent at Canterbury not be used in advertising or publicity pertaining to
 * distribution of the software without specific, written prior permission.
 * Richard Hesketh and The University of Kent at Canterbury make no
 * representations about the suitability of this software for any purpose.
 * It is provided "as is" without express or implied warranty.
 *
 * Richard Hesketh AND THE UNIVERSITY OF KENT AT CANTERBURY DISCLAIMS ALL
 * WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL Richard Hesketh OR THE
 * UNIVERSITY OF KENT AT CANTERBURY BE LIABLE FOR ANY SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
 * DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
 * OF THIS SOFTWARE.
 *
 * Author:  Richard Hesketh / rlh2@ukc.ac.uk, 
 *                Computing Lab. University of Kent at Canterbury, UK
 */

/* Widget Class Resources Exception Lists
 *
 * These lists define resources that cannot or should not be edited
 * .. they are either generated by the widget or are read-only
 */

/*
 * Xt Intrinsics defined WidgetClasses
 */

static ResDefsRec rect_object_res[] = {	 /* rectObjClass */
#ifdef NOT_BROKEN_RECT_OBJ
	{ XtNx, XtCX, XtRPosition, IGNORE },
	{ XtNy, XtCY, XtRPosition, IGNORE },
#else
	{ XtNx, XtCPosition, XtRPosition, IGNORE },
	{ XtNy, XtCPosition, XtRPosition, IGNORE },
#endif
	{ XtNwidth, XtCWidth, XtRDimension, IGNORE },
	{ XtNheight, XtCHeight, XtRDimension, IGNORE },
	{ XtNborderWidth, XtCBorderWidth, XtRDimension, IGNORE }
};

static ResDefsRec core_res[] = {	 /* coreWidgetClass */
	{ XtNdepth, XtCDepth, XtRInt, IGNORE },
	{ XtNtranslations, XtCTranslations, XtRTranslationTable, EDIT_ONLY }
};

static ResDefsRec composite_res[] = {	/* compositeWidgetClass */
	{ XtNchildren, XtCReadOnly, XtRWidgetList, EDIT_ONLY | READ_ONLY },
	{ XtNnumChildren, XtCReadOnly, XtRCardinal, IGNORE }
};

static ResDefsRec app_shell_res[] = {	/* applicationShellWidgetClass */
	{ XtNargc, XtCArgc, XtRInt, IGNORE }
};

/*
 * Xaw Athena Widget Set defined WidgetClasses
 */

static ResDefsRec xaw_text_res[] = {	/* textWidgetClass */
	{ XtNtextSource, XtCTextSource, XtRWidget, EDIT_ONLY | READ_ONLY },
	{ XtNtextSink, XtCTextSink, XtRWidget, EDIT_ONLY | READ_ONLY }
};

#ifdef UKC_WIDGETS
/*
 * Xukc UKC Widget Set defined WidgetClasses
 */

static ResDefsRec xukc_med3_menu_res[] = { /* UKCMed3MenuWidgetClass */
	{ XtNmenuWidget, XtCReadOnly, XtRWidget, EDIT_ONLY | READ_ONLY }
};

static ResDefsRec xukc_scr_list_res[] = { /* UKCScrListWidgetClass */
	{ XtNallowHoriz, XtCBoolean, XtRBoolean, IGNORE },
	{ XtNallowVert, XtCBoolean, XtRBoolean, IGNORE },
	{ XtNforceBars, XtCBoolean, XtRBoolean, IGNORE },
	{ XtNlistWidget, XtCReadOnly, XtRWidget, EDIT_ONLY | READ_ONLY },
	{ XtNnumberStrings, XtCNumberStrings, XtRCardinal, EDIT_ONLY | READ_ONLY },
	{ XtNlist, XtCList, XtRPointer, IGNORE }
};

static ResDefsRec xukc_label_res[] = { /* UKCLabelWidgetClass */
	{ XtNoldLabel, XtCOldLabel, XtRString, IGNORE }
};

static ResDefsRec xukc_toggle_res[] = { /* UKCToggleWidgetClass */
	{ XtNleftPixmap, XtCLeftPixmap, XtRPixmap, IGNORE },
	{ XtNrightPixmap, XtCRightPixmap, XtRPixmap, IGNORE },
	{ XtNleftBitmap, XtCLeftBitmap, XtRBitmap, IGNORE },
	{ XtNrightBitmap, XtCRightBitmap, XtRBitmap, IGNORE }
};

static ResDefsRec xukc_value_res[] = { /* UKCValueWidgetClass */
	{ XtNminWidth, XtCMinWidth, XtRDimension, IGNORE },
	{ XtNminHeight, XtCMinHeight, XtRDimension, IGNORE },
	{ XtNhorizColor, XtCForeground, XtRPixel, IGNORE },
	{ XtNvertColor, XtCForeground, XtRPixel, IGNORE },
	{ XtNdecArrow, XtCReadOnly, XtRWidget, EDIT_ONLY | READ_ONLY },
	{ XtNincArrow, XtCReadOnly, XtRWidget, EDIT_ONLY | READ_ONLY },
	{ XtNvalueText, XtCReadOnly, XtRWidget, EDIT_ONLY | READ_ONLY },
};

static ResDefsRec xukc_viewport_res[] = { /* UKCViewportWidgetClass */
	{ XtNdefaultDistance, XtCThickness, XtRInt, IGNORE },
	{ XtNclipWidget, XtCReadOnly, XtRWidget, EDIT_ONLY | READ_ONLY },
	{ XtNhorizScroll, XtCReadOnly, XtRWidget, EDIT_ONLY | READ_ONLY },
	{ XtNscrolledChild, XtCReadOnly, XtRWidget, EDIT_ONLY | READ_ONLY },
	{ XtNvertScroll, XtCReadOnly, XtRWidget, EDIT_ONLY | READ_ONLY }
};
#endif /* UKC_WIDGETS */
