#ifndef WI_perly_layout_h
#define WI_perly_layout_h
/* $Id: perly_layout.h,v 1.3 91/12/17 12:00:17 rlh2 Rel $
 *
 * X Toolkit program layout header file.
 * This file contains all the definitions of the static parts
 * of the user interface.
 */

/*
 * This file was generated by the DIRT interface editor
 *	Author: Richard Hesketh / rlh2@ukc.ac.uk
 *	Version: 1.3 (Wc) of July 1990
 *
 * Generated for rlh2 on Mon Dec 16 16:30:37 1991
 */

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Xukc/RowCol.h>
#include <X11/Xukc/Viewport.h>
#include <X11/Xaw/Form.h>
#include <X11/Xukc/Error.h>
#include <X11/Xaw/AsciiText.h>
#include <X11/Xaw/Paned.h>
#include <X11/Xukc/Value.h>
#include <X11/Xukc/Toggle.h>
#include <X11/Xukc/Label.h>
#include <X11/Xukc/Layout.h>
#include <X11/Shell.h>
#include <X11/Xaw/Label.h>
#include <X11/Core.h>
#include <X11/Xukc/Command.h>
#include <X11/Xaw/Box.h>

struct w_connections {
	Widget *layout;
	Widget *w1;
	Widget *w2;
	Positioning pos;
};

/* WIDGET/OBJECT class registration list */

struct w_classes {
	WidgetClass *class;
	String class_name;
};

/* WIDGET/OBJECT constructor registration list */

struct w_constructors {
	Widget (*constructor)();
	String constructor_name;
};

struct w_classes WI_perly_classes[] = {
	{ &ukcRowColWidgetClass, "ukcRowColWidgetClass" },
	{ &ukcViewportWidgetClass, "ukcViewportWidgetClass" },
	{ &formWidgetClass, "formWidgetClass" },
	{ &ukcErrorWidgetClass, "ukcErrorWidgetClass" },
	{ &asciiTextWidgetClass, "asciiTextWidgetClass" },
	{ &panedWidgetClass, "panedWidgetClass" },
	{ &ukcValueWidgetClass, "ukcValueWidgetClass" },
	{ &ukcToggleWidgetClass, "ukcToggleWidgetClass" },
	{ &ukcLabelWidgetClass, "ukcLabelWidgetClass" },
	{ &ukcLayoutWidgetClass, "ukcLayoutWidgetClass" },
	{ &labelWidgetClass, "labelWidgetClass" },
	{ &ukcCommandWidgetClass, "ukcCommandWidgetClass" },
	{ &boxWidgetClass, "boxWidgetClass" },
};

struct w_constructors WI_perly_constructors[] = {
	{ XtCreateApplicationShell, "XtCreateApplicationShell" },
};

/* WIDGET ID. VARIABLES */

Widget WI_perly;
Widget  WI_perly_box;
Widget   WI_perly_button;
Widget   WI_transparent;
Widget   WI_perly_icon;
Widget  WI_tailor_popup;
Widget   WI_tailor_layout;
Widget    WI_hide_tailor_button;
Widget    WI_perly_tailor_title;
Widget    WI_tailor_output_label;
Widget    WI_tailor_popup_on_output;
Widget    WI_tailor_popup_on_completion;
Widget    WI_tailor_popup_never;
Widget    WI_tailor_icon_label;
Widget    WI_tailor_icon_on_when_output;
Widget    WI_on_completion_options;
Widget    WI_beep_on_completion;
Widget    WI_show_quit_button;
Widget    WI_pass_args;
Widget    WI_execution_directory;
Widget    WI_execution_directory_title;
Widget    WI_label_tailoring_title;
Widget    WI_font_title;
Widget    WI_font_button;
Widget    WI_foreground_title;
Widget    WI_foreground_button;
Widget    WI_background_title;
Widget    WI_background_button;
Widget    WI_bar_colour_title;
Widget    WI_bar_colour_button;
Widget    WI_highlight_colour_title;
Widget    WI_highlight_colour_button;
Widget    WI_highlight_thickness_title;
Widget    WI_highlight_thickness;
Widget    WI_internal_width;
Widget    WI_internal_height;
Widget    WI_internal_height_title;
Widget    WI_internal_width_title;
Widget    WI_bitmap_title;
Widget    WI_left_bitmap_title;
Widget    WI_right_bitmap_title;
Widget    WI_right_bitmap_button;
Widget    WI_left_bitmap_button;
Widget    WI_bitmap_button;
Widget    WI_tailor_icon_always_on;
Widget    WI_tailor_icon_always_off;
Widget    WI_popdown_on_completion;
Widget    WI_auto_clear;
Widget    WI_args_title;
Widget    WI_split_args;
Widget  WI_edit_popup;
Widget   WI_edit_layout;
Widget    WI_hide_edit_button;
Widget    WI_edit_pane;
Widget     WI_output_pane;
Widget      WI_stdout_output_layout;
Widget       WI_stdout_text;
Widget       WI_stdout_clear;
Widget       WI_stdout_title;
Widget      WI_stderr_output_layout;
Widget       WI_stderr_text;
Widget       WI_stderr_clear;
Widget       WI_stderr_title;
Widget     WI_edit_script;
Widget    WI_perly_edit_title;
Widget    WI_execute_button;
Widget    WI_edit_button;
Widget    WI_blank;
Widget    WI_interrupt_button;
Widget    WI_quit_button;
Widget    WI_pause_button;
Widget  WI_error_popup;
Widget   WI_error_window;
Widget  WI_attribute_popup;
Widget   WI_attribute_form;
Widget    WI_attribute_bitmap;
Widget    WI_attribute_add;
Widget    WI_attribute_delete;
Widget    WI_attribute_hide;
Widget    WI_attribute_viewport;
Widget     WI_attribute_table;


/* RUNTIME BINDING STRUCTURE */

struct w_bind_list {
	Widget *w;
	String str;
};

struct w_bind_list WI_perly_bind_list[] = {
	{ &WI_perly_box, "*perlyBox" },
	{ &WI_perly_button, "*perlyButton" },
	{ &WI_transparent, "*transparent" },
	{ &WI_perly_icon, "*perlyIcon" },
	{ &WI_tailor_popup, "*tailorPopup" },
	{ &WI_tailor_layout, "*tailorLayout" },
	{ &WI_hide_tailor_button, "*hideTailorButton" },
	{ &WI_perly_tailor_title, "*perlyTailorTitle" },
	{ &WI_tailor_output_label, "*tailorOutputLabel" },
	{ &WI_tailor_popup_on_output, "*tailorPopupOnOutput" },
	{ &WI_tailor_popup_on_completion, "*tailorPopupOnCompletion" },
	{ &WI_tailor_popup_never, "*tailorPopupNever" },
	{ &WI_tailor_icon_label, "*tailorIconLabel" },
	{ &WI_tailor_icon_on_when_output, "*tailorIconOnWhenOutput" },
	{ &WI_on_completion_options, "*onCompletionOptions" },
	{ &WI_beep_on_completion, "*beepOnCompletion" },
	{ &WI_show_quit_button, "*showQuitButton" },
	{ &WI_pass_args, "*passArgs" },
	{ &WI_execution_directory, "*executionDirectory" },
	{ &WI_execution_directory_title, "*executionDirectoryTitle" },
	{ &WI_label_tailoring_title, "*labelTailoringTitle" },
	{ &WI_font_title, "*fontTitle" },
	{ &WI_font_button, "*fontButton" },
	{ &WI_foreground_title, "*foregroundTitle" },
	{ &WI_foreground_button, "*foregroundButton" },
	{ &WI_background_title, "*backgroundTitle" },
	{ &WI_background_button, "*backgroundButton" },
	{ &WI_bar_colour_title, "*barColourTitle" },
	{ &WI_bar_colour_button, "*barColourButton" },
	{ &WI_highlight_colour_title, "*highlightColourTitle" },
	{ &WI_highlight_colour_button, "*highlightColourButton" },
	{ &WI_highlight_thickness_title, "*highlightThicknessTitle" },
	{ &WI_highlight_thickness, "*highlightThickness" },
	{ &WI_internal_width, "*internalWidth" },
	{ &WI_internal_height, "*internalHeight" },
	{ &WI_internal_height_title, "*internalHeightTitle" },
	{ &WI_internal_width_title, "*internalWidthTitle" },
	{ &WI_bitmap_title, "*bitmapTitle" },
	{ &WI_left_bitmap_title, "*leftBitmapTitle" },
	{ &WI_right_bitmap_title, "*rightBitmapTitle" },
	{ &WI_right_bitmap_button, "*rightBitmapButton" },
	{ &WI_left_bitmap_button, "*leftBitmapButton" },
	{ &WI_bitmap_button, "*bitmapButton" },
	{ &WI_tailor_icon_always_on, "*tailorIconAlwaysOn" },
	{ &WI_tailor_icon_always_off, "*tailorIconAlwaysOff" },
	{ &WI_popdown_on_completion, "*popdownOnCompletion" },
	{ &WI_auto_clear, "*autoClear" },
	{ &WI_args_title, "*argsTitle" },
	{ &WI_split_args, "*splitArgs" },
	{ &WI_edit_popup, "*editPopup" },
	{ &WI_edit_layout, "*editLayout" },
	{ &WI_hide_edit_button, "*hideEditButton" },
	{ &WI_edit_pane, "*editPane" },
	{ &WI_output_pane, "*outputPane" },
	{ &WI_stdout_output_layout, "*stdoutOutputLayout" },
	{ &WI_stdout_text, "*stdoutText" },
	{ &WI_stdout_clear, "*stdoutClear" },
	{ &WI_stdout_title, "*stdoutTitle" },
	{ &WI_stderr_output_layout, "*stderrOutputLayout" },
	{ &WI_stderr_text, "*stderrText" },
	{ &WI_stderr_clear, "*stderrClear" },
	{ &WI_stderr_title, "*stderrTitle" },
	{ &WI_edit_script, "*editScript" },
	{ &WI_perly_edit_title, "*perlyEditTitle" },
	{ &WI_execute_button, "*executeButton" },
	{ &WI_edit_button, "*editButton" },
	{ &WI_blank, "*blank" },
	{ &WI_interrupt_button, "*interruptButton" },
	{ &WI_quit_button, "*quitButton" },
	{ &WI_pause_button, "*pauseButton" },
	{ &WI_error_popup, "*errorPopup" },
	{ &WI_error_window, "*errorWindow" },
	{ &WI_attribute_popup, "*attributePopup" },
	{ &WI_attribute_form, "*attributeForm" },
	{ &WI_attribute_bitmap, "*attributeBitmap" },
	{ &WI_attribute_add, "*attributeAdd" },
	{ &WI_attribute_delete, "*attributeDelete" },
	{ &WI_attribute_hide, "*attributeHide" },
	{ &WI_attribute_viewport, "*attributeViewport" },
	{ &WI_attribute_table, "*attributeTable" },
};

/* ACTION REGISTRATION LIST */

String WI_perly_action_names[] = {
	"tailor_popup",
	"save_perly",
	"quit_perly",
	"perly_popup",
	"perly_move",
};


/* LAYOUT CONNECTIONS */

/* widget connection list for UKCLayout widgets */
struct w_connections WI_perly_widget_connections[] = {
	{ &WI_edit_layout, &WI_perly_edit_title, &WI_edit_layout, vertical_above },
	{ &WI_edit_layout, &WI_perly_edit_title, &WI_edit_layout, horizontal_before },
	{ &WI_edit_layout, &WI_execute_button, &WI_edit_layout, vertical_above },
	{ &WI_edit_layout, &WI_execute_button, &WI_perly_edit_title, horizontal_before },
	{ &WI_edit_layout, &WI_interrupt_button, &WI_edit_layout, vertical_above },
	{ &WI_edit_layout, &WI_interrupt_button, &WI_execute_button, horizontal_before },
	{ &WI_edit_layout, &WI_pause_button, &WI_edit_layout, vertical_above },
	{ &WI_edit_layout, &WI_pause_button, &WI_interrupt_button, horizontal_before },
	{ &WI_edit_layout, &WI_edit_button, &WI_edit_layout, vertical_above },
	{ &WI_edit_layout, &WI_edit_button, &WI_pause_button, horizontal_before },
	{ &WI_edit_layout, &WI_quit_button, &WI_edit_layout, vertical_above },
	{ &WI_edit_layout, &WI_quit_button, &WI_edit_button, horizontal_before },
	{ &WI_edit_layout, &WI_blank, &WI_edit_layout, vertical_above },
	{ &WI_edit_layout, &WI_blank, &WI_quit_button, horizontal_before },
	{ &WI_edit_layout, &WI_hide_edit_button, &WI_edit_layout, vertical_above },
	{ &WI_edit_layout, &WI_hide_edit_button, &WI_blank, horizontal_before },
	{ &WI_edit_layout, &WI_edit_pane, &WI_perly_edit_title, vertical_above },
	{ &WI_edit_layout, &WI_edit_pane, &WI_execute_button, vertical_above },
	{ &WI_edit_layout, &WI_edit_pane, &WI_edit_button, vertical_above },
	{ &WI_edit_layout, &WI_edit_pane, &WI_hide_edit_button, vertical_above },
	{ &WI_edit_layout, &WI_edit_pane, &WI_quit_button, vertical_above },
	{ &WI_edit_layout, &WI_edit_pane, &WI_blank, vertical_above },
	{ &WI_edit_layout, &WI_edit_pane, &WI_interrupt_button, vertical_above },
	{ &WI_edit_layout, &WI_edit_pane, &WI_pause_button, vertical_above },
	{ &WI_edit_layout, &WI_edit_pane, &WI_edit_layout, horizontal_before },
	{ &WI_stdout_output_layout, &WI_stdout_title, &WI_stdout_output_layout, horizontal_before },
	{ &WI_stdout_output_layout, &WI_stdout_title, &WI_stdout_output_layout, vertical_above },
	{ &WI_stdout_output_layout, &WI_stdout_clear, &WI_stdout_title, horizontal_before },
	{ &WI_stdout_output_layout, &WI_stdout_clear, &WI_stdout_output_layout, vertical_above },
	{ &WI_stdout_output_layout, &WI_stdout_text, &WI_stdout_output_layout, horizontal_before },
	{ &WI_stdout_output_layout, &WI_stdout_text, &WI_stdout_clear, vertical_above },
	{ &WI_stdout_output_layout, &WI_stdout_text, &WI_stdout_title, vertical_above },
	{ &WI_stderr_output_layout, &WI_stderr_title, &WI_stderr_output_layout, horizontal_before },
	{ &WI_stderr_output_layout, &WI_stderr_title, &WI_stderr_output_layout, vertical_above },
	{ &WI_stderr_output_layout, &WI_stderr_clear, &WI_stderr_title, horizontal_before },
	{ &WI_stderr_output_layout, &WI_stderr_clear, &WI_stderr_output_layout, vertical_above },
	{ &WI_stderr_output_layout, &WI_stderr_text, &WI_stderr_output_layout, horizontal_before },
	{ &WI_stderr_output_layout, &WI_stderr_text, &WI_stderr_clear, vertical_above },
	{ &WI_stderr_output_layout, &WI_stderr_text, &WI_stderr_title, vertical_above },
	{ &WI_tailor_layout, &WI_perly_tailor_title, &WI_tailor_output_label, vertical_below },
	{ &WI_tailor_layout, &WI_hide_tailor_button, &WI_tailor_popup_never, vertical_below },
	{ &WI_tailor_layout, &WI_tailor_output_label, &WI_tailor_icon_label, vertical_below },
	{ &WI_tailor_layout, &WI_tailor_icon_label, &WI_on_completion_options, vertical_below },
	{ &WI_tailor_layout, &WI_on_completion_options, &WI_args_title, vertical_below },
	{ &WI_tailor_layout, &WI_args_title, &WI_execution_directory_title, vertical_below },
	{ &WI_tailor_layout, &WI_execution_directory_title, &WI_label_tailoring_title, vertical_below },
	{ &WI_tailor_layout, &WI_perly_tailor_title, &WI_tailor_popup_on_output, vertical_below },
	{ &WI_tailor_layout, &WI_perly_tailor_title, &WI_tailor_popup_on_completion, vertical_below },
	{ &WI_tailor_layout, &WI_perly_tailor_title, &WI_tailor_popup_never, vertical_below },
	{ &WI_tailor_layout, &WI_perly_tailor_title, &WI_hide_tailor_button, horizontal_after },
	{ &WI_tailor_layout, &WI_hide_tailor_button, &WI_tailor_layout, vertical_above },
	{ &WI_tailor_layout, &WI_perly_tailor_title, &WI_tailor_layout, vertical_above },
	{ &WI_tailor_layout, &WI_perly_tailor_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_tailor_popup_on_output, &WI_tailor_icon_on_when_output, vertical_below },
	{ &WI_tailor_layout, &WI_tailor_popup_on_completion, &WI_tailor_icon_always_on, vertical_below },
	{ &WI_tailor_layout, &WI_tailor_popup_never, &WI_tailor_icon_always_off, vertical_below },
	{ &WI_tailor_layout, &WI_tailor_icon_on_when_output, &WI_beep_on_completion, vertical_below },
	{ &WI_tailor_layout, &WI_tailor_icon_always_on, &WI_popdown_on_completion, vertical_below },
	{ &WI_tailor_layout, &WI_tailor_icon_always_off, &WI_show_quit_button, vertical_below },
	{ &WI_tailor_layout, &WI_tailor_output_label, &WI_tailor_popup_on_output, horizontal_after },
	{ &WI_tailor_layout, &WI_tailor_popup_on_output, &WI_tailor_popup_on_completion, horizontal_after },
	{ &WI_tailor_layout, &WI_tailor_popup_on_completion, &WI_tailor_popup_never, horizontal_after },
	{ &WI_tailor_layout, &WI_tailor_icon_label, &WI_tailor_icon_on_when_output, horizontal_after },
	{ &WI_tailor_layout, &WI_tailor_icon_on_when_output, &WI_tailor_icon_always_on, horizontal_after },
	{ &WI_tailor_layout, &WI_tailor_icon_always_on, &WI_tailor_icon_always_off, horizontal_after },
	{ &WI_tailor_layout, &WI_on_completion_options, &WI_beep_on_completion, horizontal_after },
	{ &WI_tailor_layout, &WI_beep_on_completion, &WI_popdown_on_completion, horizontal_after },
	{ &WI_tailor_layout, &WI_popdown_on_completion, &WI_show_quit_button, horizontal_after },
	{ &WI_tailor_layout, &WI_tailor_output_label, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_tailor_icon_label, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_on_completion_options, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_args_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_execution_directory_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_args_title, &WI_pass_args, horizontal_after },
	{ &WI_tailor_layout, &WI_pass_args, &WI_split_args, horizontal_after },
	{ &WI_tailor_layout, &WI_split_args, &WI_auto_clear, horizontal_after },
	{ &WI_tailor_layout, &WI_execution_directory_title, &WI_execution_directory, horizontal_after },
	{ &WI_tailor_layout, &WI_beep_on_completion, &WI_pass_args, vertical_below },
	{ &WI_tailor_layout, &WI_label_tailoring_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_popdown_on_completion, &WI_split_args, vertical_below },
	{ &WI_tailor_layout, &WI_show_quit_button, &WI_auto_clear, vertical_below },
	{ &WI_tailor_layout, &WI_pass_args, &WI_execution_directory, vertical_below },
	{ &WI_tailor_layout, &WI_split_args, &WI_execution_directory, vertical_below },
	{ &WI_tailor_layout, &WI_auto_clear, &WI_execution_directory, vertical_below },
	{ &WI_tailor_layout, &WI_execution_directory, &WI_label_tailoring_title, vertical_below },
	{ &WI_tailor_layout, &WI_label_tailoring_title, &WI_font_title, vertical_below },
	{ &WI_tailor_layout, &WI_label_tailoring_title, &WI_font_button, vertical_below },
	{ &WI_tailor_layout, &WI_font_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_font_title, &WI_font_button, horizontal_after },
	{ &WI_tailor_layout, &WI_foreground_title, &WI_foreground_button, horizontal_after },
	{ &WI_tailor_layout, &WI_font_button, &WI_foreground_title, vertical_below },
	{ &WI_tailor_layout, &WI_font_button, &WI_foreground_button, vertical_below },
	{ &WI_tailor_layout, &WI_font_button, &WI_background_title, vertical_below },
	{ &WI_tailor_layout, &WI_font_button, &WI_background_button, vertical_below },
	{ &WI_tailor_layout, &WI_foreground_button, &WI_background_title, horizontal_after },
	{ &WI_tailor_layout, &WI_background_title, &WI_background_button, horizontal_after },
	{ &WI_tailor_layout, &WI_foreground_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_foreground_title, &WI_bar_colour_title, vertical_below },
	{ &WI_tailor_layout, &WI_bar_colour_title, &WI_internal_width_title, vertical_below },
	{ &WI_tailor_layout, &WI_internal_width_title, &WI_internal_height_title, vertical_below },
	{ &WI_tailor_layout, &WI_internal_height_title, &WI_bitmap_title, vertical_below },
	{ &WI_tailor_layout, &WI_bitmap_title, &WI_left_bitmap_title, vertical_below },
	{ &WI_tailor_layout, &WI_left_bitmap_title, &WI_right_bitmap_title, vertical_below },
	{ &WI_tailor_layout, &WI_internal_width_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_internal_height_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_bar_colour_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_bar_colour_title, &WI_bar_colour_button, horizontal_after },
	{ &WI_tailor_layout, &WI_bar_colour_button, &WI_highlight_colour_title, horizontal_after },
	{ &WI_tailor_layout, &WI_highlight_colour_title, &WI_highlight_colour_button, horizontal_after },
	{ &WI_tailor_layout, &WI_background_title, &WI_highlight_colour_title, vertical_below },
	{ &WI_tailor_layout, &WI_bitmap_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_left_bitmap_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_right_bitmap_title, &WI_tailor_layout, horizontal_before },
	{ &WI_tailor_layout, &WI_foreground_button, &WI_bar_colour_button, vertical_below },
	{ &WI_tailor_layout, &WI_bar_colour_button, &WI_internal_width, vertical_below },
	{ &WI_tailor_layout, &WI_internal_width, &WI_highlight_thickness_title, horizontal_after },
	{ &WI_tailor_layout, &WI_internal_width_title, &WI_internal_width, horizontal_after },
	{ &WI_tailor_layout, &WI_background_button, &WI_highlight_colour_button, vertical_below },
	{ &WI_tailor_layout, &WI_highlight_colour_title, &WI_highlight_thickness_title, vertical_below },
	{ &WI_tailor_layout, &WI_highlight_colour_button, &WI_highlight_thickness, vertical_below },
	{ &WI_tailor_layout, &WI_highlight_thickness, &WI_internal_height, vertical_below },
	{ &WI_tailor_layout, &WI_highlight_thickness_title, &WI_internal_height, vertical_below },
	{ &WI_tailor_layout, &WI_internal_height, &WI_bitmap_button, vertical_below },
	{ &WI_tailor_layout, &WI_internal_width, &WI_internal_height, vertical_below },
	{ &WI_tailor_layout, &WI_left_bitmap_title, &WI_left_bitmap_button, horizontal_after },
	{ &WI_tailor_layout, &WI_right_bitmap_title, &WI_right_bitmap_button, horizontal_after },
	{ &WI_tailor_layout, &WI_left_bitmap_button, &WI_right_bitmap_button, vertical_below },
	{ &WI_tailor_layout, &WI_bitmap_button, &WI_left_bitmap_button, vertical_below },
	{ &WI_tailor_layout, &WI_internal_height_title, &WI_internal_height, horizontal_after },
};

/* END */
#endif /* WI_perly_layout_h */
