#ifndef lint
static char rcsid[] =
   "$Id: resource_create.c,v 1.2 91/12/17 12:00:20 rlh2 Rel $";
#endif /* !lint */

/*
 * This file was generated by the DIRT interface editor
 *	Author: Richard Hesketh / rlh2@ukc.ac.uk
 *	Version: 1.3 (Wc) of July 1990
 *
 * Generated for rlh2 on Mon Dec 16 16:32:38 1991
 */

#include <X11/IntrinsicP.h>
#include <X11/ShellP.h>
#include <X11/Wc/WcCreate.h>
#include <X11/Xukc/Layout.h>

/* fixes for Wcl constructor registration */
#define XtCreateApplicationShell WcCreateApplicationShell
extern Widget WcCreateApplicationShell();
#define XtCreateOverrideShell WcCreateOverrideShell
extern Widget WcCreateOverrideShell();
#define XtCreateShell WcCreateShell
extern Widget WcCreateShell();
#define XtCreateTopLevelShell WcCreateTopLevelShell
extern Widget WcCreateTopLevelShell();
#define XtCreateTransientShell WcCreateTransientShell
extern Widget WcCreateTransientShell();
#define XtCreateWMShell WcCreateWMShell
extern Widget WcCreateWMShell();
#define XtCreateVendorShell WcCreateVendorShell
extern Widget WcCreateVendorShell();

#include "resource_layout.h"


create_connections(connections, j)
struct w_connections connections[];
Cardinal j;
{
	Cardinal i;

	for (i=0; i < j; i++)
		if (connections[i].layout != NULL
		    && *connections[i].layout != NULL) {
			XukcLayoutAddConnection(*(connections[i].layout),
						*(connections[i].w1),
						*(connections[i].w2),
						connections[i].pos);
			connections[i].layout = NULL;
		}
}



Display *
XukcToolkitInitialize(dpy_str, app_name, app_class, argc, argv,
				options, num_options, app_defaults)
String dpy_str;
String app_name;
String app_class;
Cardinal *argc;
String argv[];
XrmOptionDescRec options[];
Cardinal num_options;
String *app_defaults;
{
	static Boolean inited = FALSE;
	XtAppContext new_context;
	Display *dpy;
	Cardinal i = 1;

	if (!inited) {
		XtToolkitInitialize();
		inited = TRUE;
	}

	new_context = XtCreateApplicationContext();
	XtAppSetFallbackResources(new_context, app_defaults);
	dpy = XtOpenDisplay(new_context, dpy_str, app_name,
				app_class, options, num_options,
				argc, argv);
	if (dpy == NULL) {
		XtErrorMsg("invalidDisplay", "xukcToolkitInitialize",
			"XukcToolkitError",
			(dpy_str == NULL ? "Can't Open Display" :
			 "Can't Open Display %s"), &dpy_str, &i);
	}

	WcRegisterIntrinsic(new_context);

	for (i = 0; i < XtNumber(WI_res_ed_classes); i++)
		WcRegisterClassPtr(new_context,
			WI_res_ed_classes[i].class_name,
			*(WI_res_ed_classes[i].class));

	return (dpy);
}


XukcDirtRegisterApplicationDefaults(screen, defs, n_defs)
Screen *screen;
String defs[];
Cardinal n_defs;
{
	XrmDatabase rdb = NULL;
	Cardinal i;

	for (i = 0; i < n_defs; i++)
		XrmPutLineResource(&rdb, defs[i]);

	if (rdb != NULL) {
#if defined(XlibSpecificationRelease) && XlibSpecificationRelease > 4
		XrmDatabase sdb = XtScreenDatabase(screen);

		XrmCombineDatabase(rdb, &sdb, False);
#else
		XrmMergeDatabases(DisplayOfScreen(screen)->db, &rdb);
		DisplayOfScreen(screen)->db = rdb;
		/* original dpy->db has been destroyed */
#endif
	}
}


Widget
XukcDirtGO(dpy_str, argc, argv, options, num_options, app_defaults)
String dpy_str;
Cardinal *argc;
String argv[];
XrmOptionDescRec options[];
Cardinal num_options;
String app_defaults[];
{
	Widget new_shell;
	Display *dpy;

	dpy = XukcToolkitInitialize(dpy_str, "resEd", "ResEd",
					argc, argv, options, num_options,
					app_defaults);
	new_shell = XtAppCreateShell("resEd", "ResEd",
					applicationShellWidgetClass, dpy,
					(ArgList)NULL, 0);
	return (new_shell);
}


void
XukcDirtAddLayoutConnections()
{
	create_connections(WI_res_ed_widget_connections,
			XtNumber(WI_res_ed_widget_connections));
}

void
XukcCreateUserInterface(toplevel_shell)
Widget toplevel_shell;
{
	Cardinal i;

	WI_res_ed = toplevel_shell;

	/* create all the widgets in the user interface */
	WcWidgetCreation(toplevel_shell);

	/* bind the widget ids. to variables */
	for (i = 0; i < XtNumber(WI_res_ed_bind_list); i++) {
		*(WI_res_ed_bind_list[i].w) = WcFullNameToWidget(toplevel_shell,
			WI_res_ed_bind_list[i].str);
		if (*(WI_res_ed_bind_list[i].w) == NULL) {
			printf("WI_res_ed: failed to bind user interface.  Missing defaults file?\n");
			exit(1);
		}
	}

	XukcDirtAddLayoutConnections();
}
