#ifndef WI_res_ed_layout_h
#define WI_res_ed_layout_h
/* $Id: resource_layout.h,v 1.2 91/12/17 12:00:21 rlh2 Rel $
 *
 * X Toolkit program layout header file.
 * This file contains all the definitions of the static parts
 * of the user interface.
 */

/*
 * This file was generated by the DIRT interface editor
 *	Author: Richard Hesketh / rlh2@ukc.ac.uk
 *	Version: 1.3 (Wc) of July 1990
 *
 * Generated for rlh2 on Mon Dec 16 16:32:38 1991
 */

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Xukc/Scaled.h>
#include <X11/Xukc/Viewport.h>
#include <X11/Xaw/Paned.h>
#include <X11/Xukc/Med3Menu.h>
#include <X11/Xukc/Label.h>
#include <X11/Xukc/Mouse.h>
#include <X11/Xukc/Layout.h>

struct w_connections {
	Widget *layout;
	Widget *w1;
	Widget *w2;
	Positioning pos;
};

/* WIDGET/OBJECT class registration list */

struct w_classes {
	WidgetClass *class;
	String class_name;
};

/* WIDGET/OBJECT constructor registration list */

struct w_constructors {
	Widget (*constructor)();
	String constructor_name;
};

struct w_classes WI_res_ed_classes[] = {
	{ &ukcScaledWidgetClass, "ukcScaledWidgetClass" },
	{ &ukcViewportWidgetClass, "ukcViewportWidgetClass" },
	{ &panedWidgetClass, "panedWidgetClass" },
	{ &ukcMed3MenuWidgetClass, "ukcMed3MenuWidgetClass" },
	{ &ukcLabelWidgetClass, "ukcLabelWidgetClass" },
	{ &ukcMouseWidgetClass, "ukcMouseWidgetClass" },
	{ &ukcLayoutWidgetClass, "ukcLayoutWidgetClass" },
};

/* WIDGET ID. VARIABLES */

Widget WI_res_ed;
Widget  WI_main_layout;
Widget   WI_mouse_hole;
Widget   WI_title;
Widget   WI_main_menu;
Widget   WI_main_pane;
Widget    WI_horiz_pane1;
Widget     WI_vert_layout_h1;
Widget      WI_resource_view4;
Widget     WI_vert_layout_h2;
Widget      WI_global_view2;
Widget    WI_horiz_pane2;
Widget     WI_vert_layout1_h;
Widget      WI_history_log2;
Widget     WI_vert_layout2_h;
Widget      WI_zoom_view2;


/* RUNTIME BINDING STRUCTURE */

struct w_bind_list {
	Widget *w;
	String str;
};

struct w_bind_list WI_res_ed_bind_list[] = {
	{ &WI_main_layout, "*mainLayout" },
	{ &WI_mouse_hole, "*mouseHole" },
	{ &WI_title, "*title" },
	{ &WI_main_menu, "*mainMenu" },
	{ &WI_main_pane, "*mainPane" },
	{ &WI_horiz_pane1, "*horizPane1" },
	{ &WI_vert_layout_h1, "*vertLayoutH1" },
	{ &WI_resource_view4, "*resourceView4" },
	{ &WI_vert_layout_h2, "*vertLayoutH2" },
	{ &WI_global_view2, "*globalView2" },
	{ &WI_horiz_pane2, "*horizPane2" },
	{ &WI_vert_layout1_h, "*vertLayout1H" },
	{ &WI_history_log2, "*historyLog2" },
	{ &WI_vert_layout2_h, "*vertLayout2H" },
	{ &WI_zoom_view2, "*zoomView2" },
};


/* LAYOUT CONNECTIONS */

/* widget connection list for UKCLayout widgets */
struct w_connections WI_res_ed_widget_connections[] = {
	{ &WI_main_layout, &WI_title, &WI_main_layout, vertical_above },
	{ &WI_main_layout, &WI_title, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_title, &WI_main_menu, vertical_below },
	{ &WI_main_layout, &WI_main_menu, &WI_main_layout, horizontal_before },
	{ &WI_main_layout, &WI_mouse_hole, &WI_main_layout, vertical_above },
	{ &WI_main_layout, &WI_mouse_hole, &WI_title, horizontal_before },
	{ &WI_main_layout, &WI_main_menu, &WI_mouse_hole, horizontal_after },
	{ &WI_main_layout, &WI_main_menu, &WI_main_pane, vertical_below },
	{ &WI_main_layout, &WI_mouse_hole, &WI_main_pane, vertical_below },
	{ &WI_vert_layout1_h, &WI_history_log2, &WI_vert_layout1_h, horizontal_before },
	{ &WI_vert_layout1_h, &WI_vert_layout1_h, &WI_history_log2, vertical_below },
	{ &WI_vert_layout_h1, &WI_vert_layout_h1, &WI_resource_view4, horizontal_after },
	{ &WI_vert_layout_h1, &WI_vert_layout_h1, &WI_resource_view4, vertical_below },
	{ &WI_vert_layout_h2, &WI_vert_layout_h2, &WI_global_view2, vertical_below },
	{ &WI_vert_layout2_h, &WI_zoom_view2, &WI_vert_layout2_h, horizontal_before },
	{ &WI_vert_layout_h2, &WI_global_view2, &WI_vert_layout_h2, horizontal_before },
	{ &WI_vert_layout2_h, &WI_vert_layout2_h, &WI_zoom_view2, vertical_below },
};

/* END */
#endif /* WI_res_ed_layout_h */
