#ifndef WI_xscan_layout_h
#define WI_xscan_layout_h
/* $Id: xscan_layout.h,v 1.2 91/12/17 12:00:22 rlh2 Rel $
 *
 * X Toolkit program layout header file.
 * This file contains all the definitions of the static parts
 * of the user interface.
 */

/*
 * This file was generated by the DIRT interface editor
 *	Author: Richard Hesketh / rlh2@ukc.ac.uk
 *	Version: 1.3 (Wc) of July 1990
 *
 * Generated for rlh2 on Mon Dec 16 16:28:30 1991
 */

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Xukc/Value.h>
#include <X11/Xukc/Toggle.h>
#include <X11/Xaw/AsciiText.h>
#include <X11/Xukc/Command.h>
#include <X11/Xukc/Passive.h>
#include <X11/Xukc/Med3Menu.h>
#include <X11/Xukc/Label.h>
#include <X11/Xukc/Layout.h>

/* WIDGET/OBJECT class registration list */

struct w_classes {
	WidgetClass *class;
	String class_name;
};

/* WIDGET/OBJECT constructor registration list */

struct w_constructors {
	Widget (*constructor)();
	String constructor_name;
};

struct w_classes WI_xscan_classes[] = {
	{ &ukcValueWidgetClass, "ukcValueWidgetClass" },
	{ &ukcToggleWidgetClass, "ukcToggleWidgetClass" },
	{ &asciiTextWidgetClass, "asciiTextWidgetClass" },
	{ &ukcCommandWidgetClass, "ukcCommandWidgetClass" },
	{ &ukcPassiveWidgetClass, "ukcPassiveWidgetClass" },
	{ &ukcMed3MenuWidgetClass, "ukcMed3MenuWidgetClass" },
	{ &ukcLabelWidgetClass, "ukcLabelWidgetClass" },
	{ &ukcLayoutWidgetClass, "ukcLayoutWidgetClass" },
};

/* WIDGET ID. VARIABLES */

Widget WI_xscan;
Widget  WI_main_layout;
Widget   WI_main_title;
Widget   WI_quit_button;
Widget   WI_preview_scan;
Widget   WI_preview_button;
Widget   WI_scan_button;
Widget   WI_image_file_button;
Widget   WI_image_file;
Widget   WI_res_layout;
Widget    WI_dpi75;
Widget    WI_dpi150;
Widget    WI_dpi300;
Widget    WI_dpi_custom;
Widget    WI_res_title;
Widget    WI_x_res_title;
Widget    WI_x_res_min;
Widget    WI_x_res;
Widget    WI_x_res_max;
Widget    WI_y_res_title;
Widget    WI_y_res_min;
Widget    WI_y_res;
Widget    WI_y_res_max;
Widget   WI_scale_layout;
Widget    WI_scale_title;
Widget    WI_x_scale_title;
Widget    WI_x_scale_min;
Widget    WI_x_scale;
Widget    WI_x_scale_max;
Widget    WI_y_scale_title;
Widget    WI_y_scale_min;
Widget    WI_y_scale;
Widget    WI_y_scale_max;
Widget   WI_intensity_layout;
Widget    WI_intensity_title;
Widget    WI_intensity_min;
Widget    WI_intensity;
Widget    WI_intensity_max;
Widget    WI_contrast_title;
Widget    WI_contrast_min;
Widget    WI_contrast;
Widget    WI_contrast_max;
Widget    WI_invert_image;
Widget    WI_mirror_image;
Widget    WI_auto_background;
Widget   WI_scan_layout;
Widget    WI_scan_title;
Widget    WI_x_start_title;
Widget    WI_x_start;
Widget    WI_y_start_title;
Widget    WI_y_start;
Widget    WI_x_extent_title;
Widget    WI_x_extent;
Widget    WI_y_extent_title;
Widget    WI_y_extent;
Widget   WI_output_layout;
Widget    WI_dithered_title;
Widget    WI_fat8;
Widget    WI_fat4;
Widget    WI_bayer;
Widget    WI_vertical;
Widget    WI_pattern_title;
Widget    WI_pattern_file;
Widget    WI_output_bitmap;
Widget    WI_greyscale4_bit;
Widget    WI_greyscale7_bit;
Widget    WI_greyscale8_bit;


/* RUNTIME BINDING STRUCTURE */

struct w_bind_list {
	Widget *w;
	String str;
};

struct w_bind_list WI_xscan_bind_list[] = {
	{ &WI_main_layout, "*mainLayout" },
	{ &WI_main_title, "*mainTitle" },
	{ &WI_quit_button, "*quitButton" },
	{ &WI_preview_scan, "*previewScan" },
	{ &WI_preview_button, "*previewButton" },
	{ &WI_scan_button, "*scanButton" },
	{ &WI_image_file_button, "*imageFileButton" },
	{ &WI_image_file, "*imageFile" },
	{ &WI_res_layout, "*resLayout" },
	{ &WI_dpi75, "*dpi75" },
	{ &WI_dpi150, "*dpi150" },
	{ &WI_dpi300, "*dpi300" },
	{ &WI_dpi_custom, "*dpiCustom" },
	{ &WI_res_title, "*resTitle" },
	{ &WI_x_res_title, "*xResTitle" },
	{ &WI_x_res_min, "*xResMin" },
	{ &WI_x_res, "*xRes" },
	{ &WI_x_res_max, "*xResMax" },
	{ &WI_y_res_title, "*yResTitle" },
	{ &WI_y_res_min, "*yResMin" },
	{ &WI_y_res, "*yRes" },
	{ &WI_y_res_max, "*yResMax" },
	{ &WI_scale_layout, "*scaleLayout" },
	{ &WI_scale_title, "*scaleTitle" },
	{ &WI_x_scale_title, "*xScaleTitle" },
	{ &WI_x_scale_min, "*xScaleMin" },
	{ &WI_x_scale, "*xScale" },
	{ &WI_x_scale_max, "*xScaleMax" },
	{ &WI_y_scale_title, "*yScaleTitle" },
	{ &WI_y_scale_min, "*yScaleMin" },
	{ &WI_y_scale, "*yScale" },
	{ &WI_y_scale_max, "*yScaleMax" },
	{ &WI_intensity_layout, "*intensityLayout" },
	{ &WI_intensity_title, "*intensityTitle" },
	{ &WI_intensity_min, "*intensityMin" },
	{ &WI_intensity, "*intensity" },
	{ &WI_intensity_max, "*intensityMax" },
	{ &WI_contrast_title, "*contrastTitle" },
	{ &WI_contrast_min, "*contrastMin" },
	{ &WI_contrast, "*contrast" },
	{ &WI_contrast_max, "*contrastMax" },
	{ &WI_invert_image, "*invertImage" },
	{ &WI_mirror_image, "*mirrorImage" },
	{ &WI_auto_background, "*autoBackground" },
	{ &WI_scan_layout, "*scanLayout" },
	{ &WI_scan_title, "*scanTitle" },
	{ &WI_x_start_title, "*xStartTitle" },
	{ &WI_x_start, "*xStart" },
	{ &WI_y_start_title, "*yStartTitle" },
	{ &WI_y_start, "*yStart" },
	{ &WI_x_extent_title, "*xExtentTitle" },
	{ &WI_x_extent, "*xExtent" },
	{ &WI_y_extent_title, "*yExtentTitle" },
	{ &WI_y_extent, "*yExtent" },
	{ &WI_output_layout, "*outputLayout" },
	{ &WI_dithered_title, "*ditheredTitle" },
	{ &WI_fat8, "*fat8" },
	{ &WI_fat4, "*fat4" },
	{ &WI_bayer, "*bayer" },
	{ &WI_vertical, "*vertical" },
	{ &WI_pattern_title, "*patternTitle" },
	{ &WI_pattern_file, "*patternFile" },
	{ &WI_output_bitmap, "*outputBitmap" },
	{ &WI_greyscale4_bit, "*greyscale4Bit" },
	{ &WI_greyscale7_bit, "*greyscale7Bit" },
	{ &WI_greyscale8_bit, "*greyscale8Bit" },
};

/* ACTION REGISTRATION LIST */

String WI_xscan_action_names[] = {
	"StartNewDrag",
	"EndDrag",
	"DragBox",
};


/* LAYOUT CONNECTIONS */
/* END */
#endif /* WI_xscan_layout_h */
